

/****************************************************************/
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/****************************************************************/
#ifndef _M_0_AUTO_H_
#define _M_0_AUTO_H_

/* Function Configuration Information */
#define FS_M_0_FUNCTION_NUMBER 0 
#define FS_M_0_TABLE_SELECT 0 
#define FS_M_0_NUM_PARMS 0x0000 

/* Parameter Definitions */
#define DEBUG_LOOP_CNT_LIMIT_ADDR  0x0007
#define TRACE_LOOP_CNT_LIMIT_ADDR  0x0008

#endif

