/*===========================================================================*/
/* Module      = dr7f701378_irq.h                                            */
/* Version     = V1.10                                                       */
/*               extracted from device file dr7f701378.dvf                   */
/*               generated by DeFiXRH850 1.0.2.5                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2018 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701378                                    */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701378_IRQ_H
#define __R7F701378_IRQ_H

#define IRQ_TABLE_START                 0x00000200u

#define RESET_ENABLE                    0x00000001u

// #define SYSERR_ENABLE                   0x00000010u
#ifndef SYSERR_ENABLE                  
  #define SYSERR_ENABLE                   0x00000000u
#endif

// #define HVTRAP_ENABLE                   0x00000020u
#ifndef HVTRAP_ENABLE                  
  #define HVTRAP_ENABLE                   0x00000000u
#endif

// #define FETRAPEX_ENABLE                 0x00000030u
#ifndef FETRAPEX_ENABLE                
  #define FETRAPEX_ENABLE                 0x00000000u
#endif

// #define EITRAP0_ENABLE                  0x00000040u
#ifndef EITRAP0_ENABLE                 
  #define EITRAP0_ENABLE                  0x00000000u
#endif

// #define EITRAP1_ENABLE                  0x00000050u
#ifndef EITRAP1_ENABLE                 
  #define EITRAP1_ENABLE                  0x00000000u
#endif

// #define RIEX_ENABLE                     0x00000060u
#ifndef RIEX_ENABLE                    
  #define RIEX_ENABLE                     0x00000000u
#endif

// #define UCPOP_ENABLE                    0x00000080u
#ifndef UCPOP_ENABLE                   
  #define UCPOP_ENABLE                    0x00000000u
#endif

// #define MIP_MDP_ENABLE                  0x00000090u
#ifndef MIP_MDP_ENABLE                 
  #define MIP_MDP_ENABLE                  0x00000000u
#endif

// #define PIEX_ENABLE                     0x000000A0u
#ifndef PIEX_ENABLE                    
  #define PIEX_ENABLE                     0x00000000u
#endif

// #define MAEX_ENABLE                     0x000000C0u
#ifndef MAEX_ENABLE                    
  #define MAEX_ENABLE                     0x00000000u
#endif

// #define FENMI_ENABLE                    0x000000E0u
#ifndef FENMI_ENABLE                   
  #define FENMI_ENABLE                    0x00000000u
#endif

// #define FEINT_ENABLE                    0x000000F0u
#ifndef FEINT_ENABLE                   
  #define FEINT_ENABLE                    0x00000000u
#endif

// #define EINTPRIO_0_ENABLE               0x00000100u
#ifndef EINTPRIO_0_ENABLE              
  #define EINTPRIO_0_ENABLE               0x00000000u
#endif

// #define EINTPRIO_1_ENABLE               0x00000110u
#ifndef EINTPRIO_1_ENABLE              
  #define EINTPRIO_1_ENABLE               0x00000000u
#endif

// #define EINTPRIO_2_ENABLE               0x00000120u
#ifndef EINTPRIO_2_ENABLE              
  #define EINTPRIO_2_ENABLE               0x00000000u
#endif

// #define EINTPRIO_3_ENABLE               0x00000130u
#ifndef EINTPRIO_3_ENABLE              
  #define EINTPRIO_3_ENABLE               0x00000000u
#endif

// #define EINTPRIO_4_ENABLE               0x00000140u
#ifndef EINTPRIO_4_ENABLE              
  #define EINTPRIO_4_ENABLE               0x00000000u
#endif

// #define EINTPRIO_5_ENABLE               0x00000150u
#ifndef EINTPRIO_5_ENABLE              
  #define EINTPRIO_5_ENABLE               0x00000000u
#endif

// #define EINTPRIO_6_ENABLE               0x00000160u
#ifndef EINTPRIO_6_ENABLE              
  #define EINTPRIO_6_ENABLE               0x00000000u
#endif

// #define EINTPRIO_7_ENABLE               0x00000170u
#ifndef EINTPRIO_7_ENABLE              
  #define EINTPRIO_7_ENABLE               0x00000000u
#endif

// #define EINTPRIO_8_ENABLE               0x00000180u
#ifndef EINTPRIO_8_ENABLE              
  #define EINTPRIO_8_ENABLE               0x00000000u
#endif

// #define EINTPRIO_9_ENABLE               0x00000190u
#ifndef EINTPRIO_9_ENABLE              
  #define EINTPRIO_9_ENABLE               0x00000000u
#endif

// #define EINTPRIO_10_ENABLE              0x000001A0u
#ifndef EINTPRIO_10_ENABLE             
  #define EINTPRIO_10_ENABLE              0x00000000u
#endif

// #define EINTPRIO_11_ENABLE              0x000001B0u
#ifndef EINTPRIO_11_ENABLE             
  #define EINTPRIO_11_ENABLE              0x00000000u
#endif

// #define EINTPRIO_12_ENABLE              0x000001C0u
#ifndef EINTPRIO_12_ENABLE             
  #define EINTPRIO_12_ENABLE              0x00000000u
#endif

// #define EINTPRIO_13_ENABLE              0x000001D0u
#ifndef EINTPRIO_13_ENABLE             
  #define EINTPRIO_13_ENABLE              0x00000000u
#endif

// #define EINTPRIO_14_ENABLE              0x000001E0u
#ifndef EINTPRIO_14_ENABLE             
  #define EINTPRIO_14_ENABLE              0x00000000u
#endif

// #define EINTPRIO_15_ENABLE              0x000001F0u
#ifndef EINTPRIO_15_ENABLE             
  #define EINTPRIO_15_ENABLE              0x00000000u
#endif


// #define INTECM_ENABLE                   (IRQ_TABLE_START + 0x00000020u)
#ifndef INTECM_ENABLE                  
  #define INTECM_ENABLE                   0x00000000u
#endif

// #define INTWDTA0_ENABLE                 (IRQ_TABLE_START + 0x00000024u)
#ifndef INTWDTA0_ENABLE                
  #define INTWDTA0_ENABLE                 0x00000000u
#endif

// #define INTDMA0_ENABLE                  (IRQ_TABLE_START + 0x00000040u)
#ifndef INTDMA0_ENABLE                 
  #define INTDMA0_ENABLE                  0x00000000u
#endif

// #define INTDMA1_ENABLE                  (IRQ_TABLE_START + 0x00000044u)
#ifndef INTDMA1_ENABLE                 
  #define INTDMA1_ENABLE                  0x00000000u
#endif

// #define INTDMA2_ENABLE                  (IRQ_TABLE_START + 0x00000048u)
#ifndef INTDMA2_ENABLE                 
  #define INTDMA2_ENABLE                  0x00000000u
#endif

// #define INTDMA3_ENABLE                  (IRQ_TABLE_START + 0x0000004Cu)
#ifndef INTDMA3_ENABLE                 
  #define INTDMA3_ENABLE                  0x00000000u
#endif

// #define INTDMA4_ENABLE                  (IRQ_TABLE_START + 0x00000050u)
#ifndef INTDMA4_ENABLE                 
  #define INTDMA4_ENABLE                  0x00000000u
#endif

// #define INTDMA5_ENABLE                  (IRQ_TABLE_START + 0x00000054u)
#ifndef INTDMA5_ENABLE                 
  #define INTDMA5_ENABLE                  0x00000000u
#endif

// #define INTDMA6_ENABLE                  (IRQ_TABLE_START + 0x00000058u)
#ifndef INTDMA6_ENABLE                 
  #define INTDMA6_ENABLE                  0x00000000u
#endif

// #define INTDMA7_ENABLE                  (IRQ_TABLE_START + 0x0000005Cu)
#ifndef INTDMA7_ENABLE                 
  #define INTDMA7_ENABLE                  0x00000000u
#endif

// #define INTDMA8_ENABLE                  (IRQ_TABLE_START + 0x00000060u)
#ifndef INTDMA8_ENABLE                 
  #define INTDMA8_ENABLE                  0x00000000u
#endif

// #define INTDMA9_ENABLE                  (IRQ_TABLE_START + 0x00000064u)
#ifndef INTDMA9_ENABLE                 
  #define INTDMA9_ENABLE                  0x00000000u
#endif

// #define INTDMA10_ENABLE                 (IRQ_TABLE_START + 0x00000068u)
#ifndef INTDMA10_ENABLE                
  #define INTDMA10_ENABLE                 0x00000000u
#endif

// #define INTDMA11_ENABLE                 (IRQ_TABLE_START + 0x0000006Cu)
#ifndef INTDMA11_ENABLE                
  #define INTDMA11_ENABLE                 0x00000000u
#endif

// #define INTDMA12_ENABLE                 (IRQ_TABLE_START + 0x00000070u)
#ifndef INTDMA12_ENABLE                
  #define INTDMA12_ENABLE                 0x00000000u
#endif

// #define INTDMA13_ENABLE                 (IRQ_TABLE_START + 0x00000074u)
#ifndef INTDMA13_ENABLE                
  #define INTDMA13_ENABLE                 0x00000000u
#endif

// #define INTDMA14_ENABLE                 (IRQ_TABLE_START + 0x00000078u)
#ifndef INTDMA14_ENABLE                
  #define INTDMA14_ENABLE                 0x00000000u
#endif

// #define INTDMA15_ENABLE                 (IRQ_TABLE_START + 0x0000007Cu)
#ifndef INTDMA15_ENABLE                
  #define INTDMA15_ENABLE                 0x00000000u
#endif

// #define INTP0_ENABLE                    (IRQ_TABLE_START + 0x00000080u)
#ifndef INTP0_ENABLE                   
  #define INTP0_ENABLE                    0x00000000u
#endif

// #define INTP1_ENABLE                    (IRQ_TABLE_START + 0x00000084u)
#ifndef INTP1_ENABLE                   
  #define INTP1_ENABLE                    0x00000000u
#endif

// #define INTP2_ENABLE                    (IRQ_TABLE_START + 0x00000088u)
#ifndef INTP2_ENABLE                   
  #define INTP2_ENABLE                    0x00000000u
#endif

// #define INTP3_ENABLE                    (IRQ_TABLE_START + 0x0000008Cu)
#ifndef INTP3_ENABLE                   
  #define INTP3_ENABLE                    0x00000000u
#endif

// #define INTP4_ENABLE                    (IRQ_TABLE_START + 0x00000090u)
#ifndef INTP4_ENABLE                   
  #define INTP4_ENABLE                    0x00000000u
#endif

// #define INTTSG30I0_ENABLE               (IRQ_TABLE_START + 0x000000A0u)
#ifndef INTTSG30I0_ENABLE              
  #define INTTSG30I0_ENABLE               0x00000000u
#endif

// #define INTTSG30I1_ENABLE               (IRQ_TABLE_START + 0x000000A4u)
#ifndef INTTSG30I1_ENABLE              
  #define INTTSG30I1_ENABLE               0x00000000u
#endif

// #define INTTSG30I2_ENABLE               (IRQ_TABLE_START + 0x000000A8u)
#ifndef INTTSG30I2_ENABLE              
  #define INTTSG30I2_ENABLE               0x00000000u
#endif

// #define INTTSG30I3_ENABLE               (IRQ_TABLE_START + 0x000000ACu)
#ifndef INTTSG30I3_ENABLE              
  #define INTTSG30I3_ENABLE               0x00000000u
#endif

// #define INTTSG30I4_ENABLE               (IRQ_TABLE_START + 0x000000B0u)
#ifndef INTTSG30I4_ENABLE              
  #define INTTSG30I4_ENABLE               0x00000000u
#endif

// #define INTTSG30I5_ENABLE               (IRQ_TABLE_START + 0x000000B4u)
#ifndef INTTSG30I5_ENABLE              
  #define INTTSG30I5_ENABLE               0x00000000u
#endif

// #define INTTSG30I6_ENABLE               (IRQ_TABLE_START + 0x000000B8u)
#ifndef INTTSG30I6_ENABLE              
  #define INTTSG30I6_ENABLE               0x00000000u
#endif

// #define INTTSG30I7_ENABLE               (IRQ_TABLE_START + 0x000000BCu)
#ifndef INTTSG30I7_ENABLE              
  #define INTTSG30I7_ENABLE               0x00000000u
#endif

// #define INTTSG30I8_ENABLE               (IRQ_TABLE_START + 0x000000C0u)
#ifndef INTTSG30I8_ENABLE              
  #define INTTSG30I8_ENABLE               0x00000000u
#endif

// #define INTTSG30I9_ENABLE               (IRQ_TABLE_START + 0x000000C4u)
#ifndef INTTSG30I9_ENABLE              
  #define INTTSG30I9_ENABLE               0x00000000u
#endif

// #define INTTSG30I10_ENABLE              (IRQ_TABLE_START + 0x000000C8u)
#ifndef INTTSG30I10_ENABLE             
  #define INTTSG30I10_ENABLE              0x00000000u
#endif

// #define INTTSG30I11_ENABLE              (IRQ_TABLE_START + 0x000000CCu)
#ifndef INTTSG30I11_ENABLE             
  #define INTTSG30I11_ENABLE              0x00000000u
#endif

// #define INTTSG30I12_ENABLE              (IRQ_TABLE_START + 0x000000D0u)
#ifndef INTTSG30I12_ENABLE             
  #define INTTSG30I12_ENABLE              0x00000000u
#endif

// #define INTTSG30IPEK_ENABLE             (IRQ_TABLE_START + 0x000000D4u)
#ifndef INTTSG30IPEK_ENABLE            
  #define INTTSG30IPEK_ENABLE             0x00000000u
#endif

// #define INTTSG30IVLY_ENABLE             (IRQ_TABLE_START + 0x000000D8u)
#ifndef INTTSG30IVLY_ENABLE            
  #define INTTSG30IVLY_ENABLE             0x00000000u
#endif

// #define INTTSG30IER_ENABLE              (IRQ_TABLE_START + 0x000000DCu)
#ifndef INTTSG30IER_ENABLE             
  #define INTTSG30IER_ENABLE              0x00000000u
#endif

// #define INTTSG30IWN_ENABLE              (IRQ_TABLE_START + 0x000000E0u)
#ifndef INTTSG30IWN_ENABLE             
  #define INTTSG30IWN_ENABLE              0x00000000u
#endif

// #define INTTSG31I0_ENABLE               (IRQ_TABLE_START + 0x000000E4u)
#ifndef INTTSG31I0_ENABLE              
  #define INTTSG31I0_ENABLE               0x00000000u
#endif

// #define INTTSG31I1_ENABLE               (IRQ_TABLE_START + 0x000000E8u)
#ifndef INTTSG31I1_ENABLE              
  #define INTTSG31I1_ENABLE               0x00000000u
#endif

// #define INTTSG31I2_ENABLE               (IRQ_TABLE_START + 0x000000ECu)
#ifndef INTTSG31I2_ENABLE              
  #define INTTSG31I2_ENABLE               0x00000000u
#endif

// #define INTTSG31I3_ENABLE               (IRQ_TABLE_START + 0x000000F0u)
#ifndef INTTSG31I3_ENABLE              
  #define INTTSG31I3_ENABLE               0x00000000u
#endif

// #define INTTSG31I4_ENABLE               (IRQ_TABLE_START + 0x000000F4u)
#ifndef INTTSG31I4_ENABLE              
  #define INTTSG31I4_ENABLE               0x00000000u
#endif

// #define INTTSG31I5_ENABLE               (IRQ_TABLE_START + 0x000000F8u)
#ifndef INTTSG31I5_ENABLE              
  #define INTTSG31I5_ENABLE               0x00000000u
#endif

// #define INTTSG31I6_ENABLE               (IRQ_TABLE_START + 0x000000FCu)
#ifndef INTTSG31I6_ENABLE              
  #define INTTSG31I6_ENABLE               0x00000000u
#endif

// #define INTTSG31I7_ENABLE               (IRQ_TABLE_START + 0x00000100u)
#ifndef INTTSG31I7_ENABLE              
  #define INTTSG31I7_ENABLE               0x00000000u
#endif

// #define INTTSG31I8_ENABLE               (IRQ_TABLE_START + 0x00000104u)
#ifndef INTTSG31I8_ENABLE              
  #define INTTSG31I8_ENABLE               0x00000000u
#endif

// #define INTTSG31I9_ENABLE               (IRQ_TABLE_START + 0x00000108u)
#ifndef INTTSG31I9_ENABLE              
  #define INTTSG31I9_ENABLE               0x00000000u
#endif

// #define INTTSG31I10_ENABLE              (IRQ_TABLE_START + 0x0000010Cu)
#ifndef INTTSG31I10_ENABLE             
  #define INTTSG31I10_ENABLE              0x00000000u
#endif

// #define INTTSG31I11_ENABLE              (IRQ_TABLE_START + 0x00000110u)
#ifndef INTTSG31I11_ENABLE             
  #define INTTSG31I11_ENABLE              0x00000000u
#endif

// #define INTTSG31I12_ENABLE              (IRQ_TABLE_START + 0x00000114u)
#ifndef INTTSG31I12_ENABLE             
  #define INTTSG31I12_ENABLE              0x00000000u
#endif

// #define INTTSG31IPEK_ENABLE             (IRQ_TABLE_START + 0x00000118u)
#ifndef INTTSG31IPEK_ENABLE            
  #define INTTSG31IPEK_ENABLE             0x00000000u
#endif

// #define INTTSG31IVLY_ENABLE             (IRQ_TABLE_START + 0x0000011Cu)
#ifndef INTTSG31IVLY_ENABLE            
  #define INTTSG31IVLY_ENABLE             0x00000000u
#endif

// #define INTTSG31IER_ENABLE              (IRQ_TABLE_START + 0x00000120u)
#ifndef INTTSG31IER_ENABLE             
  #define INTTSG31IER_ENABLE              0x00000000u
#endif

// #define INTTSG31IWN_ENABLE              (IRQ_TABLE_START + 0x00000124u)
#ifndef INTTSG31IWN_ENABLE             
  #define INTTSG31IWN_ENABLE              0x00000000u
#endif

// #define INTOSTM0_ENABLE                 (IRQ_TABLE_START + 0x00000128u)
#ifndef INTOSTM0_ENABLE                
  #define INTOSTM0_ENABLE                 0x00000000u
#endif

// #define INTOSTM1_ENABLE                 (IRQ_TABLE_START + 0x0000012Cu)
#ifndef INTOSTM1_ENABLE                
  #define INTOSTM1_ENABLE                 0x00000000u
#endif

// #define INTADCG0ERR_ENABLE              (IRQ_TABLE_START + 0x00000130u)
#ifndef INTADCG0ERR_ENABLE             
  #define INTADCG0ERR_ENABLE              0x00000000u
#endif

// #define INTADCG0I0_ENABLE               (IRQ_TABLE_START + 0x00000134u)
#ifndef INTADCG0I0_ENABLE              
  #define INTADCG0I0_ENABLE               0x00000000u
#endif

// #define INTADCG0I1_ENABLE               (IRQ_TABLE_START + 0x00000138u)
#ifndef INTADCG0I1_ENABLE              
  #define INTADCG0I1_ENABLE               0x00000000u
#endif

// #define INTADCG0I2_ENABLE               (IRQ_TABLE_START + 0x0000013Cu)
#ifndef INTADCG0I2_ENABLE              
  #define INTADCG0I2_ENABLE               0x00000000u
#endif

// #define INTADCG0I3_ENABLE               (IRQ_TABLE_START + 0x00000140u)
#ifndef INTADCG0I3_ENABLE              
  #define INTADCG0I3_ENABLE               0x00000000u
#endif

// #define INTADCG0I4_ENABLE               (IRQ_TABLE_START + 0x00000144u)
#ifndef INTADCG0I4_ENABLE              
  #define INTADCG0I4_ENABLE               0x00000000u
#endif

// #define INTCSIH0IRE_ENABLE              (IRQ_TABLE_START + 0x00000148u)
#ifndef INTCSIH0IRE_ENABLE             
  #define INTCSIH0IRE_ENABLE              0x00000000u
#endif

// #define INTCSIH0IR0S_ENABLE             (IRQ_TABLE_START + 0x0000014Cu)
#ifndef INTCSIH0IR0S_ENABLE            
  #define INTCSIH0IR0S_ENABLE             0x00000000u
#endif

// #define INTCSIH0IC0S_ENABLE             (IRQ_TABLE_START + 0x00000150u)
#ifndef INTCSIH0IC0S_ENABLE            
  #define INTCSIH0IC0S_ENABLE             0x00000000u
#endif

// #define INTCSIH0IR1_ENABLE              (IRQ_TABLE_START + 0x00000154u)
#ifndef INTCSIH0IR1_ENABLE             
  #define INTCSIH0IR1_ENABLE              0x00000000u
#endif

// #define INTCSIH0IC1_ENABLE              (IRQ_TABLE_START + 0x00000158u)
#ifndef INTCSIH0IC1_ENABLE             
  #define INTCSIH0IC1_ENABLE              0x00000000u
#endif

// #define INTCSIH0IR2_ENABLE              (IRQ_TABLE_START + 0x0000015Cu)
#ifndef INTCSIH0IR2_ENABLE             
  #define INTCSIH0IR2_ENABLE              0x00000000u
#endif

// #define INTCSIH0IC2_ENABLE              (IRQ_TABLE_START + 0x00000160u)
#ifndef INTCSIH0IC2_ENABLE             
  #define INTCSIH0IC2_ENABLE              0x00000000u
#endif

// #define INTCSIH0IJC_ENABLE              (IRQ_TABLE_START + 0x00000164u)
#ifndef INTCSIH0IJC_ENABLE             
  #define INTCSIH0IJC_ENABLE              0x00000000u
#endif

// #define INTCSIH1IRE_ENABLE              (IRQ_TABLE_START + 0x00000168u)
#ifndef INTCSIH1IRE_ENABLE             
  #define INTCSIH1IRE_ENABLE              0x00000000u
#endif

// #define INTCSIH1IR0S_ENABLE             (IRQ_TABLE_START + 0x0000016Cu)
#ifndef INTCSIH1IR0S_ENABLE            
  #define INTCSIH1IR0S_ENABLE             0x00000000u
#endif

// #define INTCSIH1IC0S_ENABLE             (IRQ_TABLE_START + 0x00000170u)
#ifndef INTCSIH1IC0S_ENABLE            
  #define INTCSIH1IC0S_ENABLE             0x00000000u
#endif

// #define INTCSIH1IR1_ENABLE              (IRQ_TABLE_START + 0x00000174u)
#ifndef INTCSIH1IR1_ENABLE             
  #define INTCSIH1IR1_ENABLE              0x00000000u
#endif

// #define INTCSIH1IC1_ENABLE              (IRQ_TABLE_START + 0x00000178u)
#ifndef INTCSIH1IC1_ENABLE             
  #define INTCSIH1IC1_ENABLE              0x00000000u
#endif

// #define INTCSIH1IR2_ENABLE              (IRQ_TABLE_START + 0x0000017Cu)
#ifndef INTCSIH1IR2_ENABLE             
  #define INTCSIH1IR2_ENABLE              0x00000000u
#endif

// #define INTCSIH1IC2_ENABLE              (IRQ_TABLE_START + 0x00000180u)
#ifndef INTCSIH1IC2_ENABLE             
  #define INTCSIH1IC2_ENABLE              0x00000000u
#endif

// #define INTCSIH1IJC_ENABLE              (IRQ_TABLE_START + 0x00000184u)
#ifndef INTCSIH1IJC_ENABLE             
  #define INTCSIH1IJC_ENABLE              0x00000000u
#endif

// #define INTCSIH2IRE_ENABLE              (IRQ_TABLE_START + 0x00000188u)
#ifndef INTCSIH2IRE_ENABLE             
  #define INTCSIH2IRE_ENABLE              0x00000000u
#endif

// #define INTCSIH2IR_ENABLE               (IRQ_TABLE_START + 0x0000018Cu)
#ifndef INTCSIH2IR_ENABLE              
  #define INTCSIH2IR_ENABLE               0x00000000u
#endif

// #define INTCSIH2IC_ENABLE               (IRQ_TABLE_START + 0x00000190u)
#ifndef INTCSIH2IC_ENABLE              
  #define INTCSIH2IC_ENABLE               0x00000000u
#endif

// #define INTCSIH2IJC_ENABLE              (IRQ_TABLE_START + 0x00000194u)
#ifndef INTCSIH2IJC_ENABLE             
  #define INTCSIH2IJC_ENABLE              0x00000000u
#endif

// #define INTCSIH3IRE_ENABLE              (IRQ_TABLE_START + 0x00000198u)
#ifndef INTCSIH3IRE_ENABLE             
  #define INTCSIH3IRE_ENABLE              0x00000000u
#endif

// #define INTCSIH3IR_ENABLE               (IRQ_TABLE_START + 0x0000019Cu)
#ifndef INTCSIH3IR_ENABLE              
  #define INTCSIH3IR_ENABLE               0x00000000u
#endif

// #define INTCSIH3IC_ENABLE               (IRQ_TABLE_START + 0x000001A0u)
#ifndef INTCSIH3IC_ENABLE              
  #define INTCSIH3IC_ENABLE               0x00000000u
#endif

// #define INTCSIH3IJC_ENABLE              (IRQ_TABLE_START + 0x000001A4u)
#ifndef INTCSIH3IJC_ENABLE             
  #define INTCSIH3IJC_ENABLE              0x00000000u
#endif

// #define INTSCI30ERI_ENABLE              (IRQ_TABLE_START + 0x000001A8u)
#ifndef INTSCI30ERI_ENABLE             
  #define INTSCI30ERI_ENABLE              0x00000000u
#endif

// #define INTSCI30RXI_ENABLE              (IRQ_TABLE_START + 0x000001ACu)
#ifndef INTSCI30RXI_ENABLE             
  #define INTSCI30RXI_ENABLE              0x00000000u
#endif

// #define INTSCI30TXI_ENABLE              (IRQ_TABLE_START + 0x000001B0u)
#ifndef INTSCI30TXI_ENABLE             
  #define INTSCI30TXI_ENABLE              0x00000000u
#endif

// #define INTSCI30TEI_ENABLE              (IRQ_TABLE_START + 0x000001B4u)
#ifndef INTSCI30TEI_ENABLE             
  #define INTSCI30TEI_ENABLE              0x00000000u
#endif

// #define INTSCI31ERI_ENABLE              (IRQ_TABLE_START + 0x000001B8u)
#ifndef INTSCI31ERI_ENABLE             
  #define INTSCI31ERI_ENABLE              0x00000000u
#endif

// #define INTSCI31RXI_ENABLE              (IRQ_TABLE_START + 0x000001BCu)
#ifndef INTSCI31RXI_ENABLE             
  #define INTSCI31RXI_ENABLE              0x00000000u
#endif

// #define INTSCI31TXI_ENABLE              (IRQ_TABLE_START + 0x000001C0u)
#ifndef INTSCI31TXI_ENABLE             
  #define INTSCI31TXI_ENABLE              0x00000000u
#endif

// #define INTSCI31TEI_ENABLE              (IRQ_TABLE_START + 0x000001C4u)
#ifndef INTSCI31TEI_ENABLE             
  #define INTSCI31TEI_ENABLE              0x00000000u
#endif

// #define INTRLIN30UR2_ENABLE             (IRQ_TABLE_START + 0x000001C8u)
#ifndef INTRLIN30UR2_ENABLE            
  #define INTRLIN30UR2_ENABLE             0x00000000u
#endif

// #define INTRLIN30UR1_ENABLE             (IRQ_TABLE_START + 0x000001CCu)
#ifndef INTRLIN30UR1_ENABLE            
  #define INTRLIN30UR1_ENABLE             0x00000000u
#endif

// #define INTRLIN30UR0_ENABLE             (IRQ_TABLE_START + 0x000001D0u)
#ifndef INTRLIN30UR0_ENABLE            
  #define INTRLIN30UR0_ENABLE             0x00000000u
#endif

// #define INTRLIN31UR2_ENABLE             (IRQ_TABLE_START + 0x000001D4u)
#ifndef INTRLIN31UR2_ENABLE            
  #define INTRLIN31UR2_ENABLE             0x00000000u
#endif

// #define INTRLIN31UR1_ENABLE             (IRQ_TABLE_START + 0x000001D8u)
#ifndef INTRLIN31UR1_ENABLE            
  #define INTRLIN31UR1_ENABLE             0x00000000u
#endif

// #define INTRLIN31UR0_ENABLE             (IRQ_TABLE_START + 0x000001DCu)
#ifndef INTRLIN31UR0_ENABLE            
  #define INTRLIN31UR0_ENABLE             0x00000000u
#endif

// #define INTSINT3_ENABLE                 (IRQ_TABLE_START + 0x000001E0u)
#ifndef INTSINT3_ENABLE                
  #define INTSINT3_ENABLE                 0x00000000u
#endif

// #define INTSINT4_ENABLE                 (IRQ_TABLE_START + 0x000001E4u)
#ifndef INTSINT4_ENABLE                
  #define INTSINT4_ENABLE                 0x00000000u
#endif

// #define INTP5_ENABLE                    (IRQ_TABLE_START + 0x00000200u)
#ifndef INTP5_ENABLE                   
  #define INTP5_ENABLE                    0x00000000u
#endif

// #define INTP6_ENABLE                    (IRQ_TABLE_START + 0x00000204u)
#ifndef INTP6_ENABLE                   
  #define INTP6_ENABLE                    0x00000000u
#endif

// #define INTP7_ENABLE                    (IRQ_TABLE_START + 0x00000208u)
#ifndef INTP7_ENABLE                   
  #define INTP7_ENABLE                    0x00000000u
#endif

// #define INTP8_ENABLE                    (IRQ_TABLE_START + 0x0000020Cu)
#ifndef INTP8_ENABLE                   
  #define INTP8_ENABLE                    0x00000000u
#endif

// #define INTP9_ENABLE                    (IRQ_TABLE_START + 0x00000210u)
#ifndef INTP9_ENABLE                   
  #define INTP9_ENABLE                    0x00000000u
#endif

// #define INTTAUJ0I0_ENABLE               (IRQ_TABLE_START + 0x00000214u)
#ifndef INTTAUJ0I0_ENABLE              
  #define INTTAUJ0I0_ENABLE               0x00000000u
#endif

// #define INTTAUJ0I1_ENABLE               (IRQ_TABLE_START + 0x00000218u)
#ifndef INTTAUJ0I1_ENABLE              
  #define INTTAUJ0I1_ENABLE               0x00000000u
#endif

// #define INTTAUJ0I2_ENABLE               (IRQ_TABLE_START + 0x0000021Cu)
#ifndef INTTAUJ0I2_ENABLE              
  #define INTTAUJ0I2_ENABLE               0x00000000u
#endif

// #define INTTAUJ0I3_ENABLE               (IRQ_TABLE_START + 0x00000220u)
#ifndef INTTAUJ0I3_ENABLE              
  #define INTTAUJ0I3_ENABLE               0x00000000u
#endif

// #define INTTAUJ1I0_ENABLE               (IRQ_TABLE_START + 0x00000224u)
#ifndef INTTAUJ1I0_ENABLE              
  #define INTTAUJ1I0_ENABLE               0x00000000u
#endif

// #define INTTAUJ1I1_ENABLE               (IRQ_TABLE_START + 0x00000228u)
#ifndef INTTAUJ1I1_ENABLE              
  #define INTTAUJ1I1_ENABLE               0x00000000u
#endif

// #define INTTAUJ1I2_ENABLE               (IRQ_TABLE_START + 0x0000022Cu)
#ifndef INTTAUJ1I2_ENABLE              
  #define INTTAUJ1I2_ENABLE               0x00000000u
#endif

// #define INTTAUJ1I3_ENABLE               (IRQ_TABLE_START + 0x00000230u)
#ifndef INTTAUJ1I3_ENABLE              
  #define INTTAUJ1I3_ENABLE               0x00000000u
#endif

// #define INTTAUD0I0_ENABLE               (IRQ_TABLE_START + 0x00000234u)
#ifndef INTTAUD0I0_ENABLE              
  #define INTTAUD0I0_ENABLE               0x00000000u
#endif

// #define INTTAUD0I1_ENABLE               (IRQ_TABLE_START + 0x00000238u)
#ifndef INTTAUD0I1_ENABLE              
  #define INTTAUD0I1_ENABLE               0x00000000u
#endif

// #define INTTAUD0I2_ENABLE               (IRQ_TABLE_START + 0x0000023Cu)
#ifndef INTTAUD0I2_ENABLE              
  #define INTTAUD0I2_ENABLE               0x00000000u
#endif

// #define INTTAUD0I3_ENABLE               (IRQ_TABLE_START + 0x00000240u)
#ifndef INTTAUD0I3_ENABLE              
  #define INTTAUD0I3_ENABLE               0x00000000u
#endif

// #define INTTAUD0I4_ENABLE               (IRQ_TABLE_START + 0x00000244u)
#ifndef INTTAUD0I4_ENABLE              
  #define INTTAUD0I4_ENABLE               0x00000000u
#endif

// #define INTTAUD0I5_ENABLE               (IRQ_TABLE_START + 0x00000248u)
#ifndef INTTAUD0I5_ENABLE              
  #define INTTAUD0I5_ENABLE               0x00000000u
#endif

// #define INTTAUD0I6_ENABLE               (IRQ_TABLE_START + 0x0000024Cu)
#ifndef INTTAUD0I6_ENABLE              
  #define INTTAUD0I6_ENABLE               0x00000000u
#endif

// #define INTTAUD0I7_ENABLE               (IRQ_TABLE_START + 0x00000250u)
#ifndef INTTAUD0I7_ENABLE              
  #define INTTAUD0I7_ENABLE               0x00000000u
#endif

// #define INTTAUD0I8_ENABLE               (IRQ_TABLE_START + 0x00000254u)
#ifndef INTTAUD0I8_ENABLE              
  #define INTTAUD0I8_ENABLE               0x00000000u
#endif

// #define INTTAUD0I9_ENABLE               (IRQ_TABLE_START + 0x00000258u)
#ifndef INTTAUD0I9_ENABLE              
  #define INTTAUD0I9_ENABLE               0x00000000u
#endif

// #define INTTAUD0I10_ENABLE              (IRQ_TABLE_START + 0x0000025Cu)
#ifndef INTTAUD0I10_ENABLE             
  #define INTTAUD0I10_ENABLE              0x00000000u
#endif

// #define INTTAUD0I11_ENABLE              (IRQ_TABLE_START + 0x00000260u)
#ifndef INTTAUD0I11_ENABLE             
  #define INTTAUD0I11_ENABLE              0x00000000u
#endif

// #define INTTAUD0I12_ENABLE              (IRQ_TABLE_START + 0x00000264u)
#ifndef INTTAUD0I12_ENABLE             
  #define INTTAUD0I12_ENABLE              0x00000000u
#endif

// #define INTTAUD0I13_ENABLE              (IRQ_TABLE_START + 0x00000268u)
#ifndef INTTAUD0I13_ENABLE             
  #define INTTAUD0I13_ENABLE              0x00000000u
#endif

// #define INTTAUD0I14_ENABLE              (IRQ_TABLE_START + 0x0000026Cu)
#ifndef INTTAUD0I14_ENABLE             
  #define INTTAUD0I14_ENABLE              0x00000000u
#endif

// #define INTTAUD0I15_ENABLE              (IRQ_TABLE_START + 0x00000270u)
#ifndef INTTAUD0I15_ENABLE             
  #define INTTAUD0I15_ENABLE              0x00000000u
#endif

// #define INTTAUD1I0_ENABLE               (IRQ_TABLE_START + 0x00000278u)
#ifndef INTTAUD1I0_ENABLE              
  #define INTTAUD1I0_ENABLE               0x00000000u
#endif

// #define INTTAUD1I1_ENABLE               (IRQ_TABLE_START + 0x0000027Cu)
#ifndef INTTAUD1I1_ENABLE              
  #define INTTAUD1I1_ENABLE               0x00000000u
#endif

// #define INTTAUD1I2_ENABLE               (IRQ_TABLE_START + 0x00000280u)
#ifndef INTTAUD1I2_ENABLE              
  #define INTTAUD1I2_ENABLE               0x00000000u
#endif

// #define INTTAUD1I3_ENABLE               (IRQ_TABLE_START + 0x00000284u)
#ifndef INTTAUD1I3_ENABLE              
  #define INTTAUD1I3_ENABLE               0x00000000u
#endif

// #define INTTAUD1I4_ENABLE               (IRQ_TABLE_START + 0x00000288u)
#ifndef INTTAUD1I4_ENABLE              
  #define INTTAUD1I4_ENABLE               0x00000000u
#endif

// #define INTTAUD1I5_ENABLE               (IRQ_TABLE_START + 0x0000028Cu)
#ifndef INTTAUD1I5_ENABLE              
  #define INTTAUD1I5_ENABLE               0x00000000u
#endif

// #define INTTAUD1I6_ENABLE               (IRQ_TABLE_START + 0x00000290u)
#ifndef INTTAUD1I6_ENABLE              
  #define INTTAUD1I6_ENABLE               0x00000000u
#endif

// #define INTTAUD1I7_ENABLE               (IRQ_TABLE_START + 0x00000294u)
#ifndef INTTAUD1I7_ENABLE              
  #define INTTAUD1I7_ENABLE               0x00000000u
#endif

// #define INTTAUD1I8_ENABLE               (IRQ_TABLE_START + 0x00000298u)
#ifndef INTTAUD1I8_ENABLE              
  #define INTTAUD1I8_ENABLE               0x00000000u
#endif

// #define INTTAUD1I9_ENABLE               (IRQ_TABLE_START + 0x0000029Cu)
#ifndef INTTAUD1I9_ENABLE              
  #define INTTAUD1I9_ENABLE               0x00000000u
#endif

// #define INTTAUD1I10_ENABLE              (IRQ_TABLE_START + 0x000002A0u)
#ifndef INTTAUD1I10_ENABLE             
  #define INTTAUD1I10_ENABLE              0x00000000u
#endif

// #define INTTAUD1I11_ENABLE              (IRQ_TABLE_START + 0x000002A4u)
#ifndef INTTAUD1I11_ENABLE             
  #define INTTAUD1I11_ENABLE              0x00000000u
#endif

// #define INTTAUD1I12_ENABLE              (IRQ_TABLE_START + 0x000002A8u)
#ifndef INTTAUD1I12_ENABLE             
  #define INTTAUD1I12_ENABLE              0x00000000u
#endif

// #define INTTAUD1I13_ENABLE              (IRQ_TABLE_START + 0x000002ACu)
#ifndef INTTAUD1I13_ENABLE             
  #define INTTAUD1I13_ENABLE              0x00000000u
#endif

// #define INTTAUD1I14_ENABLE              (IRQ_TABLE_START + 0x000002B0u)
#ifndef INTTAUD1I14_ENABLE             
  #define INTTAUD1I14_ENABLE              0x00000000u
#endif

// #define INTTAUD1I15_ENABLE              (IRQ_TABLE_START + 0x000002B4u)
#ifndef INTTAUD1I15_ENABLE             
  #define INTTAUD1I15_ENABLE              0x00000000u
#endif

// #define INTCSIG0IRE_ENABLE              (IRQ_TABLE_START + 0x000002B8u)
#ifndef INTCSIG0IRE_ENABLE             
  #define INTCSIG0IRE_ENABLE              0x00000000u
#endif

// #define INTCSIG0IC_ENABLE               (IRQ_TABLE_START + 0x000002BCu)
#ifndef INTCSIG0IC_ENABLE              
  #define INTCSIG0IC_ENABLE               0x00000000u
#endif

// #define INTCSIG0IR_ENABLE               (IRQ_TABLE_START + 0x000002C0u)
#ifndef INTCSIG0IR_ENABLE              
  #define INTCSIG0IR_ENABLE               0x00000000u
#endif

// #define INTADCG1ERR_ENABLE              (IRQ_TABLE_START + 0x000002C4u)
#ifndef INTADCG1ERR_ENABLE             
  #define INTADCG1ERR_ENABLE              0x00000000u
#endif

// #define INTADCG1I0_ENABLE               (IRQ_TABLE_START + 0x000002C8u)
#ifndef INTADCG1I0_ENABLE              
  #define INTADCG1I0_ENABLE               0x00000000u
#endif

// #define INTADCG1I1_ENABLE               (IRQ_TABLE_START + 0x000002CCu)
#ifndef INTADCG1I1_ENABLE              
  #define INTADCG1I1_ENABLE               0x00000000u
#endif

// #define INTADCG1I2_ENABLE               (IRQ_TABLE_START + 0x000002D0u)
#ifndef INTADCG1I2_ENABLE              
  #define INTADCG1I2_ENABLE               0x00000000u
#endif

// #define INTADCG1I3_ENABLE               (IRQ_TABLE_START + 0x000002D4u)
#ifndef INTADCG1I3_ENABLE              
  #define INTADCG1I3_ENABLE               0x00000000u
#endif

// #define INTADCG1I4_ENABLE               (IRQ_TABLE_START + 0x000002D8u)
#ifndef INTADCG1I4_ENABLE              
  #define INTADCG1I4_ENABLE               0x00000000u
#endif

// #define INTRCAN0ERR_ENABLE              (IRQ_TABLE_START + 0x000002DCu)
#ifndef INTRCAN0ERR_ENABLE             
  #define INTRCAN0ERR_ENABLE              0x00000000u
#endif

// #define INTRCAN0REC_ENABLE              (IRQ_TABLE_START + 0x000002E0u)
#ifndef INTRCAN0REC_ENABLE             
  #define INTRCAN0REC_ENABLE              0x00000000u
#endif

// #define INTRCAN0TRX_ENABLE              (IRQ_TABLE_START + 0x000002E4u)
#ifndef INTRCAN0TRX_ENABLE             
  #define INTRCAN0TRX_ENABLE              0x00000000u
#endif

// #define INTRCAN1ERR_ENABLE              (IRQ_TABLE_START + 0x000002E8u)
#ifndef INTRCAN1ERR_ENABLE             
  #define INTRCAN1ERR_ENABLE              0x00000000u
#endif

// #define INTRCAN1REC_ENABLE              (IRQ_TABLE_START + 0x000002ECu)
#ifndef INTRCAN1REC_ENABLE             
  #define INTRCAN1REC_ENABLE              0x00000000u
#endif

// #define INTRCAN1TRX_ENABLE              (IRQ_TABLE_START + 0x000002F0u)
#ifndef INTRCAN1TRX_ENABLE             
  #define INTRCAN1TRX_ENABLE              0x00000000u
#endif

// #define INTRCANGERR_ENABLE              (IRQ_TABLE_START + 0x000002F4u)
#ifndef INTRCANGERR_ENABLE             
  #define INTRCANGERR_ENABLE              0x00000000u
#endif

// #define INTRCANGRECC_ENABLE             (IRQ_TABLE_START + 0x000002F8u)
#ifndef INTRCANGRECC_ENABLE            
  #define INTRCANGRECC_ENABLE             0x00000000u
#endif

// #define INTRCAN2ERR_ENABLE              (IRQ_TABLE_START + 0x000002FCu)
#ifndef INTRCAN2ERR_ENABLE             
  #define INTRCAN2ERR_ENABLE              0x00000000u
#endif

// #define INTRCAN2REC_ENABLE              (IRQ_TABLE_START + 0x00000300u)
#ifndef INTRCAN2REC_ENABLE             
  #define INTRCAN2REC_ENABLE              0x00000000u
#endif

// #define INTRCAN2TRX_ENABLE              (IRQ_TABLE_START + 0x00000304u)
#ifndef INTRCAN2TRX_ENABLE             
  #define INTRCAN2TRX_ENABLE              0x00000000u
#endif

// #define INTFLXA0LINE0_ENABLE            (IRQ_TABLE_START + 0x00000308u)
#ifndef INTFLXA0LINE0_ENABLE           
  #define INTFLXA0LINE0_ENABLE            0x00000000u
#endif

// #define INTFLXA0LINE1_ENABLE            (IRQ_TABLE_START + 0x0000030Cu)
#ifndef INTFLXA0LINE1_ENABLE           
  #define INTFLXA0LINE1_ENABLE            0x00000000u
#endif

// #define INTFLXA0TIM0_ENABLE             (IRQ_TABLE_START + 0x00000310u)
#ifndef INTFLXA0TIM0_ENABLE            
  #define INTFLXA0TIM0_ENABLE             0x00000000u
#endif

// #define INTFLXA0TIM1_ENABLE             (IRQ_TABLE_START + 0x00000314u)
#ifndef INTFLXA0TIM1_ENABLE            
  #define INTFLXA0TIM1_ENABLE             0x00000000u
#endif

// #define INTFLXA0TIM2_ENABLE             (IRQ_TABLE_START + 0x00000318u)
#ifndef INTFLXA0TIM2_ENABLE            
  #define INTFLXA0TIM2_ENABLE             0x00000000u
#endif

// #define INTFLXA0FDA_ENABLE              (IRQ_TABLE_START + 0x0000031Cu)
#ifndef INTFLXA0FDA_ENABLE             
  #define INTFLXA0FDA_ENABLE              0x00000000u
#endif

// #define INTFLXA0FW_ENABLE               (IRQ_TABLE_START + 0x00000320u)
#ifndef INTFLXA0FW_ENABLE              
  #define INTFLXA0FW_ENABLE               0x00000000u
#endif

// #define INTFLXA0OW_ENABLE               (IRQ_TABLE_START + 0x00000324u)
#ifndef INTFLXA0OW_ENABLE              
  #define INTFLXA0OW_ENABLE               0x00000000u
#endif

// #define INTFLXA0OT_ENABLE               (IRQ_TABLE_START + 0x00000328u)
#ifndef INTFLXA0OT_ENABLE              
  #define INTFLXA0OT_ENABLE               0x00000000u
#endif

// #define INTFLXA0IQF_ENABLE              (IRQ_TABLE_START + 0x0000032Cu)
#ifndef INTFLXA0IQF_ENABLE             
  #define INTFLXA0IQF_ENABLE              0x00000000u
#endif

// #define INTFLXA0IQE_ENABLE              (IRQ_TABLE_START + 0x00000330u)
#ifndef INTFLXA0IQE_ENABLE             
  #define INTFLXA0IQE_ENABLE              0x00000000u
#endif

// #define INTSCI32ERI_ENABLE              (IRQ_TABLE_START + 0x00000368u)
#ifndef INTSCI32ERI_ENABLE             
  #define INTSCI32ERI_ENABLE              0x00000000u
#endif

// #define INTSCI32RXI_ENABLE              (IRQ_TABLE_START + 0x0000036Cu)
#ifndef INTSCI32RXI_ENABLE             
  #define INTSCI32RXI_ENABLE              0x00000000u
#endif

// #define INTSCI32TXI_ENABLE              (IRQ_TABLE_START + 0x00000370u)
#ifndef INTSCI32TXI_ENABLE             
  #define INTSCI32TXI_ENABLE              0x00000000u
#endif

// #define INTSCI32TEI_ENABLE              (IRQ_TABLE_START + 0x00000374u)
#ifndef INTSCI32TEI_ENABLE             
  #define INTSCI32TEI_ENABLE              0x00000000u
#endif

// #define INTPSI50SI_ENABLE               (IRQ_TABLE_START + 0x00000388u)
#ifndef INTPSI50SI_ENABLE              
  #define INTPSI50SI_ENABLE               0x00000000u
#endif

// #define INTPSI50RI_ENABLE               (IRQ_TABLE_START + 0x0000038Cu)
#ifndef INTPSI50RI_ENABLE              
  #define INTPSI50RI_ENABLE               0x00000000u
#endif

// #define INTPSI50TI_ENABLE               (IRQ_TABLE_START + 0x00000390u)
#ifndef INTPSI50TI_ENABLE              
  #define INTPSI50TI_ENABLE               0x00000000u
#endif

// #define INTPSI51SI_ENABLE               (IRQ_TABLE_START + 0x00000394u)
#ifndef INTPSI51SI_ENABLE              
  #define INTPSI51SI_ENABLE               0x00000000u
#endif

// #define INTPSI51RI_ENABLE               (IRQ_TABLE_START + 0x00000398u)
#ifndef INTPSI51RI_ENABLE              
  #define INTPSI51RI_ENABLE               0x00000000u
#endif

// #define INTPSI51TI_ENABLE               (IRQ_TABLE_START + 0x0000039Cu)
#ifndef INTPSI51TI_ENABLE              
  #define INTPSI51TI_ENABLE               0x00000000u
#endif

// #define INTSENT0SI_ENABLE               (IRQ_TABLE_START + 0x000003A0u)
#ifndef INTSENT0SI_ENABLE              
  #define INTSENT0SI_ENABLE               0x00000000u
#endif

// #define INTSENT0RI_ENABLE               (IRQ_TABLE_START + 0x000003A4u)
#ifndef INTSENT0RI_ENABLE              
  #define INTSENT0RI_ENABLE               0x00000000u
#endif

// #define INTSENT1SI_ENABLE               (IRQ_TABLE_START + 0x000003A8u)
#ifndef INTSENT1SI_ENABLE              
  #define INTSENT1SI_ENABLE               0x00000000u
#endif

// #define INTSENT1RI_ENABLE               (IRQ_TABLE_START + 0x000003ACu)
#ifndef INTSENT1RI_ENABLE              
  #define INTSENT1RI_ENABLE               0x00000000u
#endif

// #define INTSENT2SI_ENABLE               (IRQ_TABLE_START + 0x000003B0u)
#ifndef INTSENT2SI_ENABLE              
  #define INTSENT2SI_ENABLE               0x00000000u
#endif

// #define INTSENT2RI_ENABLE               (IRQ_TABLE_START + 0x000003B4u)
#ifndef INTSENT2RI_ENABLE              
  #define INTSENT2RI_ENABLE               0x00000000u
#endif

// #define INTSENT3SI_ENABLE               (IRQ_TABLE_START + 0x000003B8u)
#ifndef INTSENT3SI_ENABLE              
  #define INTSENT3SI_ENABLE               0x00000000u
#endif

// #define INTSENT3RI_ENABLE               (IRQ_TABLE_START + 0x000003BCu)
#ifndef INTSENT3RI_ENABLE              
  #define INTSENT3RI_ENABLE               0x00000000u
#endif

// #define INTSENT4SI_ENABLE               (IRQ_TABLE_START + 0x000003C0u)
#ifndef INTSENT4SI_ENABLE              
  #define INTSENT4SI_ENABLE               0x00000000u
#endif

// #define INTSENT4RI_ENABLE               (IRQ_TABLE_START + 0x000003C4u)
#ifndef INTSENT4RI_ENABLE              
  #define INTSENT4RI_ENABLE               0x00000000u
#endif

// #define INTSENT5SI_ENABLE               (IRQ_TABLE_START + 0x000003C8u)
#ifndef INTSENT5SI_ENABLE              
  #define INTSENT5SI_ENABLE               0x00000000u
#endif

// #define INTSENT5RI_ENABLE               (IRQ_TABLE_START + 0x000003CCu)
#ifndef INTSENT5RI_ENABLE              
  #define INTSENT5RI_ENABLE               0x00000000u
#endif

// #define INTDTSTC0_ENABLE                (IRQ_TABLE_START + 0x000003D0u)
#ifndef INTDTSTC0_ENABLE               
  #define INTDTSTC0_ENABLE                0x00000000u
#endif

// #define INTDTSTC1_ENABLE                (IRQ_TABLE_START + 0x000003D4u)
#ifndef INTDTSTC1_ENABLE               
  #define INTDTSTC1_ENABLE                0x00000000u
#endif

// #define INTDTSTC2_ENABLE                (IRQ_TABLE_START + 0x000003D8u)
#ifndef INTDTSTC2_ENABLE               
  #define INTDTSTC2_ENABLE                0x00000000u
#endif

// #define INTDTSTC3_ENABLE                (IRQ_TABLE_START + 0x000003DCu)
#ifndef INTDTSTC3_ENABLE               
  #define INTDTSTC3_ENABLE                0x00000000u
#endif

// #define INTDTSCM0_ENABLE                (IRQ_TABLE_START + 0x000003E0u)
#ifndef INTDTSCM0_ENABLE               
  #define INTDTSCM0_ENABLE                0x00000000u
#endif

// #define INTDTSCM1_ENABLE                (IRQ_TABLE_START + 0x000003E4u)
#ifndef INTDTSCM1_ENABLE               
  #define INTDTSCM1_ENABLE                0x00000000u
#endif

// #define INTDTSCM2_ENABLE                (IRQ_TABLE_START + 0x000003E8u)
#ifndef INTDTSCM2_ENABLE               
  #define INTDTSCM2_ENABLE                0x00000000u
#endif

// #define INTDTSCM3_ENABLE                (IRQ_TABLE_START + 0x000003ECu)
#ifndef INTDTSCM3_ENABLE               
  #define INTDTSCM3_ENABLE                0x00000000u
#endif

// #define INTSINT0_ENABLE                 (IRQ_TABLE_START + 0x000003F0u)
#ifndef INTSINT0_ENABLE                
  #define INTSINT0_ENABLE                 0x00000000u
#endif

// #define INTSINT1_ENABLE                 (IRQ_TABLE_START + 0x000003F4u)
#ifndef INTSINT1_ENABLE                
  #define INTSINT1_ENABLE                 0x00000000u
#endif

// #define INTSINT2_ENABLE                 (IRQ_TABLE_START + 0x000003F8u)
#ifndef INTSINT2_ENABLE                
  #define INTSINT2_ENABLE                 0x00000000u
#endif

// #define INTTAUJ2I0_ENABLE               (IRQ_TABLE_START + 0x00000400u)
#ifndef INTTAUJ2I0_ENABLE              
  #define INTTAUJ2I0_ENABLE               0x00000000u
#endif

// #define INTTAUJ2I1_ENABLE               (IRQ_TABLE_START + 0x00000404u)
#ifndef INTTAUJ2I1_ENABLE              
  #define INTTAUJ2I1_ENABLE               0x00000000u
#endif

// #define INTTAUJ2I2_ENABLE               (IRQ_TABLE_START + 0x00000408u)
#ifndef INTTAUJ2I2_ENABLE              
  #define INTTAUJ2I2_ENABLE               0x00000000u
#endif

// #define INTTAUJ2I3_ENABLE               (IRQ_TABLE_START + 0x0000040Cu)
#ifndef INTTAUJ2I3_ENABLE              
  #define INTTAUJ2I3_ENABLE               0x00000000u
#endif

// #define INTTAUD2I0_ENABLE               (IRQ_TABLE_START + 0x00000410u)
#ifndef INTTAUD2I0_ENABLE              
  #define INTTAUD2I0_ENABLE               0x00000000u
#endif

// #define INTTAUD2I1_ENABLE               (IRQ_TABLE_START + 0x00000414u)
#ifndef INTTAUD2I1_ENABLE              
  #define INTTAUD2I1_ENABLE               0x00000000u
#endif

// #define INTTAUD2I2_ENABLE               (IRQ_TABLE_START + 0x00000418u)
#ifndef INTTAUD2I2_ENABLE              
  #define INTTAUD2I2_ENABLE               0x00000000u
#endif

// #define INTTAUD2I3_ENABLE               (IRQ_TABLE_START + 0x0000041Cu)
#ifndef INTTAUD2I3_ENABLE              
  #define INTTAUD2I3_ENABLE               0x00000000u
#endif

// #define INTTAUD2I4_ENABLE               (IRQ_TABLE_START + 0x00000420u)
#ifndef INTTAUD2I4_ENABLE              
  #define INTTAUD2I4_ENABLE               0x00000000u
#endif

// #define INTTAUD2I5_ENABLE               (IRQ_TABLE_START + 0x00000424u)
#ifndef INTTAUD2I5_ENABLE              
  #define INTTAUD2I5_ENABLE               0x00000000u
#endif

// #define INTTAUD2I6_ENABLE               (IRQ_TABLE_START + 0x00000428u)
#ifndef INTTAUD2I6_ENABLE              
  #define INTTAUD2I6_ENABLE               0x00000000u
#endif

// #define INTTAUD2I7_ENABLE               (IRQ_TABLE_START + 0x0000042Cu)
#ifndef INTTAUD2I7_ENABLE              
  #define INTTAUD2I7_ENABLE               0x00000000u
#endif

// #define INTTAUD2I8_ENABLE               (IRQ_TABLE_START + 0x00000430u)
#ifndef INTTAUD2I8_ENABLE              
  #define INTTAUD2I8_ENABLE               0x00000000u
#endif

// #define INTTAUD2I9_ENABLE               (IRQ_TABLE_START + 0x00000434u)
#ifndef INTTAUD2I9_ENABLE              
  #define INTTAUD2I9_ENABLE               0x00000000u
#endif

// #define INTTAUD2I10_ENABLE              (IRQ_TABLE_START + 0x00000438u)
#ifndef INTTAUD2I10_ENABLE             
  #define INTTAUD2I10_ENABLE              0x00000000u
#endif

// #define INTTAUD2I11_ENABLE              (IRQ_TABLE_START + 0x0000043Cu)
#ifndef INTTAUD2I11_ENABLE             
  #define INTTAUD2I11_ENABLE              0x00000000u
#endif

// #define INTTAUD2I12_ENABLE              (IRQ_TABLE_START + 0x00000440u)
#ifndef INTTAUD2I12_ENABLE             
  #define INTTAUD2I12_ENABLE              0x00000000u
#endif

// #define INTTAUD2I13_ENABLE              (IRQ_TABLE_START + 0x00000444u)
#ifndef INTTAUD2I13_ENABLE             
  #define INTTAUD2I13_ENABLE              0x00000000u
#endif

// #define INTTAUD2I14_ENABLE              (IRQ_TABLE_START + 0x00000448u)
#ifndef INTTAUD2I14_ENABLE             
  #define INTTAUD2I14_ENABLE              0x00000000u
#endif

// #define INTTAUD2I15_ENABLE              (IRQ_TABLE_START + 0x0000044Cu)
#ifndef INTTAUD2I15_ENABLE             
  #define INTTAUD2I15_ENABLE              0x00000000u
#endif

// #define INTENCA0IOV_ENABLE              (IRQ_TABLE_START + 0x00000450u)
#ifndef INTENCA0IOV_ENABLE             
  #define INTENCA0IOV_ENABLE              0x00000000u
#endif

// #define INTENCA0I0_ENABLE               (IRQ_TABLE_START + 0x00000454u)
#ifndef INTENCA0I0_ENABLE              
  #define INTENCA0I0_ENABLE               0x00000000u
#endif

// #define INTENCA0I1_ENABLE               (IRQ_TABLE_START + 0x00000458u)
#ifndef INTENCA0I1_ENABLE              
  #define INTENCA0I1_ENABLE               0x00000000u
#endif

// #define INTENCA0IUD_ENABLE              (IRQ_TABLE_START + 0x0000045Cu)
#ifndef INTENCA0IUD_ENABLE             
  #define INTENCA0IUD_ENABLE              0x00000000u
#endif

// #define INTENCA0IEC_ENABLE              (IRQ_TABLE_START + 0x00000460u)
#ifndef INTENCA0IEC_ENABLE             
  #define INTENCA0IEC_ENABLE              0x00000000u
#endif

// #define INTENCA1IOV_ENABLE              (IRQ_TABLE_START + 0x00000464u)
#ifndef INTENCA1IOV_ENABLE             
  #define INTENCA1IOV_ENABLE              0x00000000u
#endif

// #define INTENCA1I0_ENABLE               (IRQ_TABLE_START + 0x00000468u)
#ifndef INTENCA1I0_ENABLE              
  #define INTENCA1I0_ENABLE               0x00000000u
#endif

// #define INTENCA1I1_ENABLE               (IRQ_TABLE_START + 0x0000046Cu)
#ifndef INTENCA1I1_ENABLE              
  #define INTENCA1I1_ENABLE               0x00000000u
#endif

// #define INTENCA1IUD_ENABLE              (IRQ_TABLE_START + 0x00000470u)
#ifndef INTENCA1IUD_ENABLE             
  #define INTENCA1IUD_ENABLE              0x00000000u
#endif

// #define INTENCA1IEC_ENABLE              (IRQ_TABLE_START + 0x00000474u)
#ifndef INTENCA1IEC_ENABLE             
  #define INTENCA1IEC_ENABLE              0x00000000u
#endif

// #define INTTPBA0IPRD_ENABLE             (IRQ_TABLE_START + 0x00000478u)
#ifndef INTTPBA0IPRD_ENABLE            
  #define INTTPBA0IPRD_ENABLE             0x00000000u
#endif

// #define INTTPBA0IDTY_ENABLE             (IRQ_TABLE_START + 0x0000047Cu)
#ifndef INTTPBA0IDTY_ENABLE            
  #define INTTPBA0IDTY_ENABLE             0x00000000u
#endif

// #define INTTPBA0IPAT_ENABLE             (IRQ_TABLE_START + 0x00000480u)
#ifndef INTTPBA0IPAT_ENABLE            
  #define INTTPBA0IPAT_ENABLE             0x00000000u
#endif

// #define INTTPBA1IPRD_ENABLE             (IRQ_TABLE_START + 0x00000484u)
#ifndef INTTPBA1IPRD_ENABLE            
  #define INTTPBA1IPRD_ENABLE             0x00000000u
#endif

// #define INTTPBA1IDTY_ENABLE             (IRQ_TABLE_START + 0x00000488u)
#ifndef INTTPBA1IDTY_ENABLE            
  #define INTTPBA1IDTY_ENABLE             0x00000000u
#endif

// #define INTTPBA1IPAT_ENABLE             (IRQ_TABLE_START + 0x0000048Cu)
#ifndef INTTPBA1IPAT_ENABLE            
  #define INTTPBA1IPAT_ENABLE             0x00000000u
#endif

// #define INTADCG0MPX_ENABLE              (IRQ_TABLE_START + 0x00000498u)
#ifndef INTADCG0MPX_ENABLE             
  #define INTADCG0MPX_ENABLE              0x00000000u
#endif

// #define INTADCG1MPX_ENABLE              (IRQ_TABLE_START + 0x0000049Cu)
#ifndef INTADCG1MPX_ENABLE             
  #define INTADCG1MPX_ENABLE              0x00000000u
#endif

// #define INTP10_ENABLE                   (IRQ_TABLE_START + 0x000004A0u)
#ifndef INTP10_ENABLE                  
  #define INTP10_ENABLE                   0x00000000u
#endif

// #define INTP11_ENABLE                   (IRQ_TABLE_START + 0x000004A4u)
#ifndef INTP11_ENABLE                  
  #define INTP11_ENABLE                   0x00000000u
#endif

// #define INTP12_ENABLE                   (IRQ_TABLE_START + 0x000004A8u)
#ifndef INTP12_ENABLE                  
  #define INTP12_ENABLE                   0x00000000u
#endif

// #define INTFLENDNM_ENABLE               (IRQ_TABLE_START + 0x000005ECu)
#ifndef INTFLENDNM_ENABLE              
  #define INTFLENDNM_ENABLE               0x00000000u
#endif

// #define INTFLERR_ENABLE                 (IRQ_TABLE_START + 0x000005FCu)
#ifndef INTFLERR_ENABLE                
  #define INTFLERR_ENABLE                 0x00000000u
#endif



#endif /* __R7F701378_IRQ_H */
