/*===========================================================================*/
/* Module      = dr7f702z19_irq_PE2.h                                        */
/* Version     = E0.90r                                                      */
/*               extracted from device file dr7f702z19.dvf                   */
/*               generated by DeFiXRH850 1.1.0.8                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2018 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F702Z19                                    */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F702Z19_IRQ_H
#define __R7F702Z19_IRQ_H

#define IRQ_TABLE_START                 0x00000200u

#define RESET_ENABLE                    0x00000001u

// #define SYSERR_ENABLE                   0x00000010u
#ifndef SYSERR_ENABLE                  
  #define SYSERR_ENABLE                   0x00000000u
#endif

// #define FETRAPEX_ENABLE                 0x00000030u
#ifndef FETRAPEX_ENABLE                
  #define FETRAPEX_ENABLE                 0x00000000u
#endif

// #define EITRAPA0_ENABLE                 0x00000040u
#ifndef EITRAPA0_ENABLE                
  #define EITRAPA0_ENABLE                 0x00000000u
#endif

// #define EITRAPA1_ENABLE                 0x00000050u
#ifndef EITRAPA1_ENABLE                
  #define EITRAPA1_ENABLE                 0x00000000u
#endif

// #define RIEX_ENABLE                     0x00000060u
#ifndef RIEX_ENABLE                    
  #define RIEX_ENABLE                     0x00000000u
#endif

// #define UCPOP_ENABLE                    0x00000080u
#ifndef UCPOP_ENABLE                   
  #define UCPOP_ENABLE                    0x00000000u
#endif

// #define MIP_MDP_ENABLE                  0x00000090u
#ifndef MIP_MDP_ENABLE                 
  #define MIP_MDP_ENABLE                  0x00000000u
#endif

// #define PIE_ENABLE                      0x000000A0u
#ifndef PIE_ENABLE                     
  #define PIE_ENABLE                      0x00000000u
#endif

// #define MAEX_ENABLE                     0x000000C0u
#ifndef MAEX_ENABLE                    
  #define MAEX_ENABLE                     0x00000000u
#endif

// #define FENMI_ENABLE                    0x000000E0u
#ifndef FENMI_ENABLE                   
  #define FENMI_ENABLE                    0x00000000u
#endif

// #define FEINT_ENABLE                    0x000000F0u
#ifndef FEINT_ENABLE                   
  #define FEINT_ENABLE                    0x00000000u
#endif

// #define EINTPRIO_0_ENABLE               0x00000100u
#ifndef EINTPRIO_0_ENABLE              
  #define EINTPRIO_0_ENABLE               0x00000000u
#endif

// #define EINTPRIO_1_ENABLE               0x00000110u
#ifndef EINTPRIO_1_ENABLE              
  #define EINTPRIO_1_ENABLE               0x00000000u
#endif

// #define EINTPRIO_2_ENABLE               0x00000120u
#ifndef EINTPRIO_2_ENABLE              
  #define EINTPRIO_2_ENABLE               0x00000000u
#endif

// #define EINTPRIO_3_ENABLE               0x00000130u
#ifndef EINTPRIO_3_ENABLE              
  #define EINTPRIO_3_ENABLE               0x00000000u
#endif

// #define EINTPRIO_4_ENABLE               0x00000140u
#ifndef EINTPRIO_4_ENABLE              
  #define EINTPRIO_4_ENABLE               0x00000000u
#endif

// #define EINTPRIO_5_ENABLE               0x00000150u
#ifndef EINTPRIO_5_ENABLE              
  #define EINTPRIO_5_ENABLE               0x00000000u
#endif

// #define EINTPRIO_6_ENABLE               0x00000160u
#ifndef EINTPRIO_6_ENABLE              
  #define EINTPRIO_6_ENABLE               0x00000000u
#endif

// #define EINTPRIO_7_ENABLE               0x00000170u
#ifndef EINTPRIO_7_ENABLE              
  #define EINTPRIO_7_ENABLE               0x00000000u
#endif

// #define EINTPRIO_8_ENABLE               0x00000180u
#ifndef EINTPRIO_8_ENABLE              
  #define EINTPRIO_8_ENABLE               0x00000000u
#endif

// #define EINTPRIO_9_ENABLE               0x00000190u
#ifndef EINTPRIO_9_ENABLE              
  #define EINTPRIO_9_ENABLE               0x00000000u
#endif

// #define EINTPRIO_10_ENABLE              0x000001A0u
#ifndef EINTPRIO_10_ENABLE             
  #define EINTPRIO_10_ENABLE              0x00000000u
#endif

// #define EINTPRIO_11_ENABLE              0x000001B0u
#ifndef EINTPRIO_11_ENABLE             
  #define EINTPRIO_11_ENABLE              0x00000000u
#endif

// #define EINTPRIO_12_ENABLE              0x000001C0u
#ifndef EINTPRIO_12_ENABLE             
  #define EINTPRIO_12_ENABLE              0x00000000u
#endif

// #define EINTPRIO_13_ENABLE              0x000001D0u
#ifndef EINTPRIO_13_ENABLE             
  #define EINTPRIO_13_ENABLE              0x00000000u
#endif

// #define EINTPRIO_14_ENABLE              0x000001E0u
#ifndef EINTPRIO_14_ENABLE             
  #define EINTPRIO_14_ENABLE              0x00000000u
#endif

// #define EINTPRIO_15_ENABLE              0x000001F0u
#ifndef EINTPRIO_15_ENABLE             
  #define EINTPRIO_15_ENABLE              0x00000000u
#endif

// #define EIINT0_ENABLE                   (IRQ_TABLE_START + 0x00000000u)
#ifndef EIINT0_ENABLE                  
  #define EIINT0_ENABLE                   0x00000000u
#endif

// #define EIINT1_ENABLE                   (IRQ_TABLE_START + 0x00000004u)
#ifndef EIINT1_ENABLE                  
  #define EIINT1_ENABLE                   0x00000000u
#endif

// #define EIINT2_ENABLE                   (IRQ_TABLE_START + 0x00000008u)
#ifndef EIINT2_ENABLE                  
  #define EIINT2_ENABLE                   0x00000000u
#endif

// #define EIINT3_ENABLE                   (IRQ_TABLE_START + 0x0000000Cu)
#ifndef EIINT3_ENABLE                  
  #define EIINT3_ENABLE                   0x00000000u
#endif

// #define EIINT4_ENABLE                   (IRQ_TABLE_START + 0x00000010u)
#ifndef EIINT4_ENABLE                  
  #define EIINT4_ENABLE                   0x00000000u
#endif

// #define EIINT5_ENABLE                   (IRQ_TABLE_START + 0x00000014u)
#ifndef EIINT5_ENABLE                  
  #define EIINT5_ENABLE                   0x00000000u
#endif

// #define EIINT6_ENABLE                   (IRQ_TABLE_START + 0x00000018u)
#ifndef EIINT6_ENABLE                  
  #define EIINT6_ENABLE                   0x00000000u
#endif

// #define EIINT7_ENABLE                   (IRQ_TABLE_START + 0x0000001Cu)
#ifndef EIINT7_ENABLE                  
  #define EIINT7_ENABLE                   0x00000000u
#endif

// #define EIINT8_ENABLE                   (IRQ_TABLE_START + 0x00000020u)
#ifndef EIINT8_ENABLE                  
  #define EIINT8_ENABLE                   0x00000000u
#endif

// #define EIINT9_ENABLE                   (IRQ_TABLE_START + 0x00000024u)
#ifndef EIINT9_ENABLE                  
  #define EIINT9_ENABLE                   0x00000000u
#endif

// #define EIINT10_ENABLE                  (IRQ_TABLE_START + 0x00000028u)
#ifndef EIINT10_ENABLE                 
  #define EIINT10_ENABLE                  0x00000000u
#endif

// #define EIINT11_ENABLE                  (IRQ_TABLE_START + 0x0000002Cu)
#ifndef EIINT11_ENABLE                 
  #define EIINT11_ENABLE                  0x00000000u
#endif

// #define EIINT12_ENABLE                  (IRQ_TABLE_START + 0x00000030u)
#ifndef EIINT12_ENABLE                 
  #define EIINT12_ENABLE                  0x00000000u
#endif

// #define EIINT13_ENABLE                  (IRQ_TABLE_START + 0x00000034u)
#ifndef EIINT13_ENABLE                 
  #define EIINT13_ENABLE                  0x00000000u
#endif

// #define EIINT14_ENABLE                  (IRQ_TABLE_START + 0x00000038u)
#ifndef EIINT14_ENABLE                 
  #define EIINT14_ENABLE                  0x00000000u
#endif

// #define EIINT15_ENABLE                  (IRQ_TABLE_START + 0x0000003Cu)
#ifndef EIINT15_ENABLE                 
  #define EIINT15_ENABLE                  0x00000000u
#endif

// #define EIINT16_ENABLE                  (IRQ_TABLE_START + 0x00000040u)
#ifndef EIINT16_ENABLE                 
  #define EIINT16_ENABLE                  0x00000000u
#endif

// #define EIINT17_ENABLE                  (IRQ_TABLE_START + 0x00000044u)
#ifndef EIINT17_ENABLE                 
  #define EIINT17_ENABLE                  0x00000000u
#endif

// #define EIINT18_ENABLE                  (IRQ_TABLE_START + 0x00000048u)
#ifndef EIINT18_ENABLE                 
  #define EIINT18_ENABLE                  0x00000000u
#endif

// #define EIINT19_ENABLE                  (IRQ_TABLE_START + 0x0000004Cu)
#ifndef EIINT19_ENABLE                 
  #define EIINT19_ENABLE                  0x00000000u
#endif

// #define EIINT20_ENABLE                  (IRQ_TABLE_START + 0x00000050u)
#ifndef EIINT20_ENABLE                 
  #define EIINT20_ENABLE                  0x00000000u
#endif

// #define EIINT21_ENABLE                  (IRQ_TABLE_START + 0x00000054u)
#ifndef EIINT21_ENABLE                 
  #define EIINT21_ENABLE                  0x00000000u
#endif

// #define EIINT22_ENABLE                  (IRQ_TABLE_START + 0x00000058u)
#ifndef EIINT22_ENABLE                 
  #define EIINT22_ENABLE                  0x00000000u
#endif

// #define EIINT23_ENABLE                  (IRQ_TABLE_START + 0x0000005Cu)
#ifndef EIINT23_ENABLE                 
  #define EIINT23_ENABLE                  0x00000000u
#endif

// #define EIINT24_ENABLE                  (IRQ_TABLE_START + 0x00000060u)
#ifndef EIINT24_ENABLE                 
  #define EIINT24_ENABLE                  0x00000000u
#endif

// #define EIINT25_ENABLE                  (IRQ_TABLE_START + 0x00000064u)
#ifndef EIINT25_ENABLE                 
  #define EIINT25_ENABLE                  0x00000000u
#endif

// #define EIINT26_ENABLE                  (IRQ_TABLE_START + 0x00000068u)
#ifndef EIINT26_ENABLE                 
  #define EIINT26_ENABLE                  0x00000000u
#endif

// #define EIINT27_ENABLE                  (IRQ_TABLE_START + 0x0000006Cu)
#ifndef EIINT27_ENABLE                 
  #define EIINT27_ENABLE                  0x00000000u
#endif

// #define EIINT28_ENABLE                  (IRQ_TABLE_START + 0x00000070u)
#ifndef EIINT28_ENABLE                 
  #define EIINT28_ENABLE                  0x00000000u
#endif

// #define EIINT29_ENABLE                  (IRQ_TABLE_START + 0x00000074u)
#ifndef EIINT29_ENABLE                 
  #define EIINT29_ENABLE                  0x00000000u
#endif

// #define EIINT30_ENABLE                  (IRQ_TABLE_START + 0x00000078u)
#ifndef EIINT30_ENABLE                 
  #define EIINT30_ENABLE                  0x00000000u
#endif

// #define EIINT31_ENABLE                  (IRQ_TABLE_START + 0x0000007Cu)
#ifndef EIINT31_ENABLE                 
  #define EIINT31_ENABLE                  0x00000000u
#endif

// #define EIINT32_ENABLE                  (IRQ_TABLE_START + 0x00000080u)
#ifndef EIINT32_ENABLE                 
  #define EIINT32_ENABLE                  0x00000000u
#endif

// #define EIINT33_ENABLE                  (IRQ_TABLE_START + 0x00000084u)
#ifndef EIINT33_ENABLE                 
  #define EIINT33_ENABLE                  0x00000000u
#endif

// #define EIINT34_ENABLE                  (IRQ_TABLE_START + 0x00000088u)
#ifndef EIINT34_ENABLE                 
  #define EIINT34_ENABLE                  0x00000000u
#endif

// #define EIINT35_ENABLE                  (IRQ_TABLE_START + 0x0000008Cu)
#ifndef EIINT35_ENABLE                 
  #define EIINT35_ENABLE                  0x00000000u
#endif

// #define EIINT36_ENABLE                  (IRQ_TABLE_START + 0x00000090u)
#ifndef EIINT36_ENABLE                 
  #define EIINT36_ENABLE                  0x00000000u
#endif

// #define EIINT37_ENABLE                  (IRQ_TABLE_START + 0x00000094u)
#ifndef EIINT37_ENABLE                 
  #define EIINT37_ENABLE                  0x00000000u
#endif

// #define EIINT38_ENABLE                  (IRQ_TABLE_START + 0x00000098u)
#ifndef EIINT38_ENABLE                 
  #define EIINT38_ENABLE                  0x00000000u
#endif

// #define EIINT39_ENABLE                  (IRQ_TABLE_START + 0x0000009Cu)
#ifndef EIINT39_ENABLE                 
  #define EIINT39_ENABLE                  0x00000000u
#endif

// #define EIINT40_ENABLE                  (IRQ_TABLE_START + 0x000000A0u)
#ifndef EIINT40_ENABLE                 
  #define EIINT40_ENABLE                  0x00000000u
#endif

// #define EIINT41_ENABLE                  (IRQ_TABLE_START + 0x000000A4u)
#ifndef EIINT41_ENABLE                 
  #define EIINT41_ENABLE                  0x00000000u
#endif

// #define EIINT42_ENABLE                  (IRQ_TABLE_START + 0x000000A8u)
#ifndef EIINT42_ENABLE                 
  #define EIINT42_ENABLE                  0x00000000u
#endif

// #define EIINT43_ENABLE                  (IRQ_TABLE_START + 0x000000ACu)
#ifndef EIINT43_ENABLE                 
  #define EIINT43_ENABLE                  0x00000000u
#endif

// #define EIINT44_ENABLE                  (IRQ_TABLE_START + 0x000000B0u)
#ifndef EIINT44_ENABLE                 
  #define EIINT44_ENABLE                  0x00000000u
#endif

// #define EIINT45_ENABLE                  (IRQ_TABLE_START + 0x000000B4u)
#ifndef EIINT45_ENABLE                 
  #define EIINT45_ENABLE                  0x00000000u
#endif

// #define EIINT46_ENABLE                  (IRQ_TABLE_START + 0x000000B8u)
#ifndef EIINT46_ENABLE                 
  #define EIINT46_ENABLE                  0x00000000u
#endif

// #define EIINT47_ENABLE                  (IRQ_TABLE_START + 0x000000BCu)
#ifndef EIINT47_ENABLE                 
  #define EIINT47_ENABLE                  0x00000000u
#endif

// #define EIINT48_ENABLE                  (IRQ_TABLE_START + 0x000000C0u)
#ifndef EIINT48_ENABLE                 
  #define EIINT48_ENABLE                  0x00000000u
#endif

// #define EIINT49_ENABLE                  (IRQ_TABLE_START + 0x000000C4u)
#ifndef EIINT49_ENABLE                 
  #define EIINT49_ENABLE                  0x00000000u
#endif

// #define EIINT50_ENABLE                  (IRQ_TABLE_START + 0x000000C8u)
#ifndef EIINT50_ENABLE                 
  #define EIINT50_ENABLE                  0x00000000u
#endif

// #define EIINT51_ENABLE                  (IRQ_TABLE_START + 0x000000CCu)
#ifndef EIINT51_ENABLE                 
  #define EIINT51_ENABLE                  0x00000000u
#endif

// #define EIINT52_ENABLE                  (IRQ_TABLE_START + 0x000000D0u)
#ifndef EIINT52_ENABLE                 
  #define EIINT52_ENABLE                  0x00000000u
#endif

// #define EIINT53_ENABLE                  (IRQ_TABLE_START + 0x000000D4u)
#ifndef EIINT53_ENABLE                 
  #define EIINT53_ENABLE                  0x00000000u
#endif

// #define EIINT54_ENABLE                  (IRQ_TABLE_START + 0x000000D8u)
#ifndef EIINT54_ENABLE                 
  #define EIINT54_ENABLE                  0x00000000u
#endif

// #define EIINT55_ENABLE                  (IRQ_TABLE_START + 0x000000DCu)
#ifndef EIINT55_ENABLE                 
  #define EIINT55_ENABLE                  0x00000000u
#endif

// #define EIINT56_ENABLE                  (IRQ_TABLE_START + 0x000000E0u)
#ifndef EIINT56_ENABLE                 
  #define EIINT56_ENABLE                  0x00000000u
#endif

// #define EIINT57_ENABLE                  (IRQ_TABLE_START + 0x000000E4u)
#ifndef EIINT57_ENABLE                 
  #define EIINT57_ENABLE                  0x00000000u
#endif

// #define EIINT58_ENABLE                  (IRQ_TABLE_START + 0x000000E8u)
#ifndef EIINT58_ENABLE                 
  #define EIINT58_ENABLE                  0x00000000u
#endif

// #define EIINT59_ENABLE                  (IRQ_TABLE_START + 0x000000ECu)
#ifndef EIINT59_ENABLE                 
  #define EIINT59_ENABLE                  0x00000000u
#endif

// #define EIINT60_ENABLE                  (IRQ_TABLE_START + 0x000000F0u)
#ifndef EIINT60_ENABLE                 
  #define EIINT60_ENABLE                  0x00000000u
#endif

// #define EIINT61_ENABLE                  (IRQ_TABLE_START + 0x000000F4u)
#ifndef EIINT61_ENABLE                 
  #define EIINT61_ENABLE                  0x00000000u
#endif

// #define EIINT62_ENABLE                  (IRQ_TABLE_START + 0x000000F8u)
#ifndef EIINT62_ENABLE                 
  #define EIINT62_ENABLE                  0x00000000u
#endif

// #define EIINT63_ENABLE                  (IRQ_TABLE_START + 0x000000FCu)
#ifndef EIINT63_ENABLE                 
  #define EIINT63_ENABLE                  0x00000000u
#endif

// #define EIINT64_ENABLE                  (IRQ_TABLE_START + 0x00000100u)
#ifndef EIINT64_ENABLE                 
  #define EIINT64_ENABLE                  0x00000000u
#endif

// #define EIINT65_ENABLE                  (IRQ_TABLE_START + 0x00000104u)
#ifndef EIINT65_ENABLE                 
  #define EIINT65_ENABLE                  0x00000000u
#endif

// #define EIINT66_ENABLE                  (IRQ_TABLE_START + 0x00000108u)
#ifndef EIINT66_ENABLE                 
  #define EIINT66_ENABLE                  0x00000000u
#endif

// #define EIINT67_ENABLE                  (IRQ_TABLE_START + 0x0000010Cu)
#ifndef EIINT67_ENABLE                 
  #define EIINT67_ENABLE                  0x00000000u
#endif

// #define EIINT68_ENABLE                  (IRQ_TABLE_START + 0x00000110u)
#ifndef EIINT68_ENABLE                 
  #define EIINT68_ENABLE                  0x00000000u
#endif

// #define EIINT69_ENABLE                  (IRQ_TABLE_START + 0x00000114u)
#ifndef EIINT69_ENABLE                 
  #define EIINT69_ENABLE                  0x00000000u
#endif

// #define EIINT70_ENABLE                  (IRQ_TABLE_START + 0x00000118u)
#ifndef EIINT70_ENABLE                 
  #define EIINT70_ENABLE                  0x00000000u
#endif

// #define EIINT71_ENABLE                  (IRQ_TABLE_START + 0x0000011Cu)
#ifndef EIINT71_ENABLE                 
  #define EIINT71_ENABLE                  0x00000000u
#endif

// #define EIINT72_ENABLE                  (IRQ_TABLE_START + 0x00000120u)
#ifndef EIINT72_ENABLE                 
  #define EIINT72_ENABLE                  0x00000000u
#endif

// #define EIINT73_ENABLE                  (IRQ_TABLE_START + 0x00000124u)
#ifndef EIINT73_ENABLE                 
  #define EIINT73_ENABLE                  0x00000000u
#endif

// #define EIINT74_ENABLE                  (IRQ_TABLE_START + 0x00000128u)
#ifndef EIINT74_ENABLE                 
  #define EIINT74_ENABLE                  0x00000000u
#endif

// #define EIINT75_ENABLE                  (IRQ_TABLE_START + 0x0000012Cu)
#ifndef EIINT75_ENABLE                 
  #define EIINT75_ENABLE                  0x00000000u
#endif

// #define EIINT76_ENABLE                  (IRQ_TABLE_START + 0x00000130u)
#ifndef EIINT76_ENABLE                 
  #define EIINT76_ENABLE                  0x00000000u
#endif

// #define EIINT77_ENABLE                  (IRQ_TABLE_START + 0x00000134u)
#ifndef EIINT77_ENABLE                 
  #define EIINT77_ENABLE                  0x00000000u
#endif

// #define EIINT78_ENABLE                  (IRQ_TABLE_START + 0x00000138u)
#ifndef EIINT78_ENABLE                 
  #define EIINT78_ENABLE                  0x00000000u
#endif

// #define EIINT79_ENABLE                  (IRQ_TABLE_START + 0x0000013Cu)
#ifndef EIINT79_ENABLE                 
  #define EIINT79_ENABLE                  0x00000000u
#endif

// #define EIINT80_ENABLE                  (IRQ_TABLE_START + 0x00000140u)
#ifndef EIINT80_ENABLE                 
  #define EIINT80_ENABLE                  0x00000000u
#endif

// #define EIINT81_ENABLE                  (IRQ_TABLE_START + 0x00000144u)
#ifndef EIINT81_ENABLE                 
  #define EIINT81_ENABLE                  0x00000000u
#endif

// #define EIINT82_ENABLE                  (IRQ_TABLE_START + 0x00000148u)
#ifndef EIINT82_ENABLE                 
  #define EIINT82_ENABLE                  0x00000000u
#endif

// #define EIINT83_ENABLE                  (IRQ_TABLE_START + 0x0000014Cu)
#ifndef EIINT83_ENABLE                 
  #define EIINT83_ENABLE                  0x00000000u
#endif

// #define EIINT84_ENABLE                  (IRQ_TABLE_START + 0x00000150u)
#ifndef EIINT84_ENABLE                 
  #define EIINT84_ENABLE                  0x00000000u
#endif

// #define EIINT85_ENABLE                  (IRQ_TABLE_START + 0x00000154u)
#ifndef EIINT85_ENABLE                 
  #define EIINT85_ENABLE                  0x00000000u
#endif

// #define EIINT86_ENABLE                  (IRQ_TABLE_START + 0x00000158u)
#ifndef EIINT86_ENABLE                 
  #define EIINT86_ENABLE                  0x00000000u
#endif

// #define EIINT87_ENABLE                  (IRQ_TABLE_START + 0x0000015Cu)
#ifndef EIINT87_ENABLE                 
  #define EIINT87_ENABLE                  0x00000000u
#endif

// #define EIINT88_ENABLE                  (IRQ_TABLE_START + 0x00000160u)
#ifndef EIINT88_ENABLE                 
  #define EIINT88_ENABLE                  0x00000000u
#endif

// #define EIINT89_ENABLE                  (IRQ_TABLE_START + 0x00000164u)
#ifndef EIINT89_ENABLE                 
  #define EIINT89_ENABLE                  0x00000000u
#endif

// #define EIINT90_ENABLE                  (IRQ_TABLE_START + 0x00000168u)
#ifndef EIINT90_ENABLE                 
  #define EIINT90_ENABLE                  0x00000000u
#endif

// #define EIINT91_ENABLE                  (IRQ_TABLE_START + 0x0000016Cu)
#ifndef EIINT91_ENABLE                 
  #define EIINT91_ENABLE                  0x00000000u
#endif

// #define EIINT92_ENABLE                  (IRQ_TABLE_START + 0x00000170u)
#ifndef EIINT92_ENABLE                 
  #define EIINT92_ENABLE                  0x00000000u
#endif

// #define EIINT93_ENABLE                  (IRQ_TABLE_START + 0x00000174u)
#ifndef EIINT93_ENABLE                 
  #define EIINT93_ENABLE                  0x00000000u
#endif

// #define EIINT94_ENABLE                  (IRQ_TABLE_START + 0x00000178u)
#ifndef EIINT94_ENABLE                 
  #define EIINT94_ENABLE                  0x00000000u
#endif

// #define EIINT95_ENABLE                  (IRQ_TABLE_START + 0x0000017Cu)
#ifndef EIINT95_ENABLE                 
  #define EIINT95_ENABLE                  0x00000000u
#endif

// #define EIINT96_ENABLE                  (IRQ_TABLE_START + 0x00000180u)
#ifndef EIINT96_ENABLE                 
  #define EIINT96_ENABLE                  0x00000000u
#endif

// #define EIINT97_ENABLE                  (IRQ_TABLE_START + 0x00000184u)
#ifndef EIINT97_ENABLE                 
  #define EIINT97_ENABLE                  0x00000000u
#endif

// #define EIINT98_ENABLE                  (IRQ_TABLE_START + 0x00000188u)
#ifndef EIINT98_ENABLE                 
  #define EIINT98_ENABLE                  0x00000000u
#endif

// #define EIINT99_ENABLE                  (IRQ_TABLE_START + 0x0000018Cu)
#ifndef EIINT99_ENABLE                 
  #define EIINT99_ENABLE                  0x00000000u
#endif

// #define EIINT100_ENABLE                 (IRQ_TABLE_START + 0x00000190u)
#ifndef EIINT100_ENABLE                
  #define EIINT100_ENABLE                 0x00000000u
#endif

// #define EIINT101_ENABLE                 (IRQ_TABLE_START + 0x00000194u)
#ifndef EIINT101_ENABLE                
  #define EIINT101_ENABLE                 0x00000000u
#endif

// #define EIINT102_ENABLE                 (IRQ_TABLE_START + 0x00000198u)
#ifndef EIINT102_ENABLE                
  #define EIINT102_ENABLE                 0x00000000u
#endif

// #define EIINT103_ENABLE                 (IRQ_TABLE_START + 0x0000019Cu)
#ifndef EIINT103_ENABLE                
  #define EIINT103_ENABLE                 0x00000000u
#endif

// #define EIINT104_ENABLE                 (IRQ_TABLE_START + 0x000001A0u)
#ifndef EIINT104_ENABLE                
  #define EIINT104_ENABLE                 0x00000000u
#endif

// #define EIINT105_ENABLE                 (IRQ_TABLE_START + 0x000001A4u)
#ifndef EIINT105_ENABLE                
  #define EIINT105_ENABLE                 0x00000000u
#endif

// #define EIINT106_ENABLE                 (IRQ_TABLE_START + 0x000001A8u)
#ifndef EIINT106_ENABLE                
  #define EIINT106_ENABLE                 0x00000000u
#endif

// #define EIINT107_ENABLE                 (IRQ_TABLE_START + 0x000001ACu)
#ifndef EIINT107_ENABLE                
  #define EIINT107_ENABLE                 0x00000000u
#endif

// #define EIINT108_ENABLE                 (IRQ_TABLE_START + 0x000001B0u)
#ifndef EIINT108_ENABLE                
  #define EIINT108_ENABLE                 0x00000000u
#endif

// #define EIINT109_ENABLE                 (IRQ_TABLE_START + 0x000001B4u)
#ifndef EIINT109_ENABLE                
  #define EIINT109_ENABLE                 0x00000000u
#endif

// #define EIINT110_ENABLE                 (IRQ_TABLE_START + 0x000001B8u)
#ifndef EIINT110_ENABLE                
  #define EIINT110_ENABLE                 0x00000000u
#endif

// #define EIINT111_ENABLE                 (IRQ_TABLE_START + 0x000001BCu)
#ifndef EIINT111_ENABLE                
  #define EIINT111_ENABLE                 0x00000000u
#endif

// #define EIINT112_ENABLE                 (IRQ_TABLE_START + 0x000001C0u)
#ifndef EIINT112_ENABLE                
  #define EIINT112_ENABLE                 0x00000000u
#endif

// #define EIINT113_ENABLE                 (IRQ_TABLE_START + 0x000001C4u)
#ifndef EIINT113_ENABLE                
  #define EIINT113_ENABLE                 0x00000000u
#endif

// #define EIINT114_ENABLE                 (IRQ_TABLE_START + 0x000001C8u)
#ifndef EIINT114_ENABLE                
  #define EIINT114_ENABLE                 0x00000000u
#endif

// #define EIINT115_ENABLE                 (IRQ_TABLE_START + 0x000001CCu)
#ifndef EIINT115_ENABLE                
  #define EIINT115_ENABLE                 0x00000000u
#endif

// #define EIINT116_ENABLE                 (IRQ_TABLE_START + 0x000001D0u)
#ifndef EIINT116_ENABLE                
  #define EIINT116_ENABLE                 0x00000000u
#endif

// #define EIINT117_ENABLE                 (IRQ_TABLE_START + 0x000001D4u)
#ifndef EIINT117_ENABLE                
  #define EIINT117_ENABLE                 0x00000000u
#endif

// #define EIINT118_ENABLE                 (IRQ_TABLE_START + 0x000001D8u)
#ifndef EIINT118_ENABLE                
  #define EIINT118_ENABLE                 0x00000000u
#endif

// #define EIINT119_ENABLE                 (IRQ_TABLE_START + 0x000001DCu)
#ifndef EIINT119_ENABLE                
  #define EIINT119_ENABLE                 0x00000000u
#endif

// #define EIINT120_ENABLE                 (IRQ_TABLE_START + 0x000001E0u)
#ifndef EIINT120_ENABLE                
  #define EIINT120_ENABLE                 0x00000000u
#endif

// #define EIINT121_ENABLE                 (IRQ_TABLE_START + 0x000001E4u)
#ifndef EIINT121_ENABLE                
  #define EIINT121_ENABLE                 0x00000000u
#endif

// #define EIINT122_ENABLE                 (IRQ_TABLE_START + 0x000001E8u)
#ifndef EIINT122_ENABLE                
  #define EIINT122_ENABLE                 0x00000000u
#endif

// #define EIINT123_ENABLE                 (IRQ_TABLE_START + 0x000001ECu)
#ifndef EIINT123_ENABLE                
  #define EIINT123_ENABLE                 0x00000000u
#endif

// #define EIINT124_ENABLE                 (IRQ_TABLE_START + 0x000001F0u)
#ifndef EIINT124_ENABLE                
  #define EIINT124_ENABLE                 0x00000000u
#endif

// #define EIINT125_ENABLE                 (IRQ_TABLE_START + 0x000001F4u)
#ifndef EIINT125_ENABLE                
  #define EIINT125_ENABLE                 0x00000000u
#endif

// #define EIINT126_ENABLE                 (IRQ_TABLE_START + 0x000001F8u)
#ifndef EIINT126_ENABLE                
  #define EIINT126_ENABLE                 0x00000000u
#endif

// #define EIINT127_ENABLE                 (IRQ_TABLE_START + 0x000001FCu)
#ifndef EIINT127_ENABLE                
  #define EIINT127_ENABLE                 0x00000000u
#endif

// #define EIINT128_ENABLE                 (IRQ_TABLE_START + 0x00000200u)
#ifndef EIINT128_ENABLE                
  #define EIINT128_ENABLE                 0x00000000u
#endif

// #define EIINT129_ENABLE                 (IRQ_TABLE_START + 0x00000204u)
#ifndef EIINT129_ENABLE                
  #define EIINT129_ENABLE                 0x00000000u
#endif

// #define EIINT130_ENABLE                 (IRQ_TABLE_START + 0x00000208u)
#ifndef EIINT130_ENABLE                
  #define EIINT130_ENABLE                 0x00000000u
#endif

// #define EIINT131_ENABLE                 (IRQ_TABLE_START + 0x0000020Cu)
#ifndef EIINT131_ENABLE                
  #define EIINT131_ENABLE                 0x00000000u
#endif

// #define EIINT132_ENABLE                 (IRQ_TABLE_START + 0x00000210u)
#ifndef EIINT132_ENABLE                
  #define EIINT132_ENABLE                 0x00000000u
#endif

// #define EIINT133_ENABLE                 (IRQ_TABLE_START + 0x00000214u)
#ifndef EIINT133_ENABLE                
  #define EIINT133_ENABLE                 0x00000000u
#endif

// #define EIINT134_ENABLE                 (IRQ_TABLE_START + 0x00000218u)
#ifndef EIINT134_ENABLE                
  #define EIINT134_ENABLE                 0x00000000u
#endif

// #define EIINT135_ENABLE                 (IRQ_TABLE_START + 0x0000021Cu)
#ifndef EIINT135_ENABLE                
  #define EIINT135_ENABLE                 0x00000000u
#endif

// #define EIINT136_ENABLE                 (IRQ_TABLE_START + 0x00000220u)
#ifndef EIINT136_ENABLE                
  #define EIINT136_ENABLE                 0x00000000u
#endif

// #define EIINT137_ENABLE                 (IRQ_TABLE_START + 0x00000224u)
#ifndef EIINT137_ENABLE                
  #define EIINT137_ENABLE                 0x00000000u
#endif

// #define EIINT138_ENABLE                 (IRQ_TABLE_START + 0x00000228u)
#ifndef EIINT138_ENABLE                
  #define EIINT138_ENABLE                 0x00000000u
#endif

// #define EIINT139_ENABLE                 (IRQ_TABLE_START + 0x0000022Cu)
#ifndef EIINT139_ENABLE                
  #define EIINT139_ENABLE                 0x00000000u
#endif

// #define EIINT140_ENABLE                 (IRQ_TABLE_START + 0x00000230u)
#ifndef EIINT140_ENABLE                
  #define EIINT140_ENABLE                 0x00000000u
#endif

// #define EIINT141_ENABLE                 (IRQ_TABLE_START + 0x00000234u)
#ifndef EIINT141_ENABLE                
  #define EIINT141_ENABLE                 0x00000000u
#endif

// #define EIINT142_ENABLE                 (IRQ_TABLE_START + 0x00000238u)
#ifndef EIINT142_ENABLE                
  #define EIINT142_ENABLE                 0x00000000u
#endif

// #define EIINT143_ENABLE                 (IRQ_TABLE_START + 0x0000023Cu)
#ifndef EIINT143_ENABLE                
  #define EIINT143_ENABLE                 0x00000000u
#endif

// #define EIINT144_ENABLE                 (IRQ_TABLE_START + 0x00000240u)
#ifndef EIINT144_ENABLE                
  #define EIINT144_ENABLE                 0x00000000u
#endif

// #define EIINT145_ENABLE                 (IRQ_TABLE_START + 0x00000244u)
#ifndef EIINT145_ENABLE                
  #define EIINT145_ENABLE                 0x00000000u
#endif

// #define EIINT146_ENABLE                 (IRQ_TABLE_START + 0x00000248u)
#ifndef EIINT146_ENABLE                
  #define EIINT146_ENABLE                 0x00000000u
#endif

// #define EIINT147_ENABLE                 (IRQ_TABLE_START + 0x0000024Cu)
#ifndef EIINT147_ENABLE                
  #define EIINT147_ENABLE                 0x00000000u
#endif

// #define EIINT148_ENABLE                 (IRQ_TABLE_START + 0x00000250u)
#ifndef EIINT148_ENABLE                
  #define EIINT148_ENABLE                 0x00000000u
#endif

// #define EIINT149_ENABLE                 (IRQ_TABLE_START + 0x00000254u)
#ifndef EIINT149_ENABLE                
  #define EIINT149_ENABLE                 0x00000000u
#endif

// #define EIINT150_ENABLE                 (IRQ_TABLE_START + 0x00000258u)
#ifndef EIINT150_ENABLE                
  #define EIINT150_ENABLE                 0x00000000u
#endif

// #define EIINT151_ENABLE                 (IRQ_TABLE_START + 0x0000025Cu)
#ifndef EIINT151_ENABLE                
  #define EIINT151_ENABLE                 0x00000000u
#endif

// #define EIINT152_ENABLE                 (IRQ_TABLE_START + 0x00000260u)
#ifndef EIINT152_ENABLE                
  #define EIINT152_ENABLE                 0x00000000u
#endif

// #define EIINT153_ENABLE                 (IRQ_TABLE_START + 0x00000264u)
#ifndef EIINT153_ENABLE                
  #define EIINT153_ENABLE                 0x00000000u
#endif

// #define EIINT154_ENABLE                 (IRQ_TABLE_START + 0x00000268u)
#ifndef EIINT154_ENABLE                
  #define EIINT154_ENABLE                 0x00000000u
#endif

// #define EIINT155_ENABLE                 (IRQ_TABLE_START + 0x0000026Cu)
#ifndef EIINT155_ENABLE                
  #define EIINT155_ENABLE                 0x00000000u
#endif

// #define EIINT156_ENABLE                 (IRQ_TABLE_START + 0x00000270u)
#ifndef EIINT156_ENABLE                
  #define EIINT156_ENABLE                 0x00000000u
#endif

// #define EIINT157_ENABLE                 (IRQ_TABLE_START + 0x00000274u)
#ifndef EIINT157_ENABLE                
  #define EIINT157_ENABLE                 0x00000000u
#endif

// #define EIINT158_ENABLE                 (IRQ_TABLE_START + 0x00000278u)
#ifndef EIINT158_ENABLE                
  #define EIINT158_ENABLE                 0x00000000u
#endif

// #define EIINT159_ENABLE                 (IRQ_TABLE_START + 0x0000027Cu)
#ifndef EIINT159_ENABLE                
  #define EIINT159_ENABLE                 0x00000000u
#endif

// #define EIINT160_ENABLE                 (IRQ_TABLE_START + 0x00000280u)
#ifndef EIINT160_ENABLE                
  #define EIINT160_ENABLE                 0x00000000u
#endif

// #define EIINT161_ENABLE                 (IRQ_TABLE_START + 0x00000284u)
#ifndef EIINT161_ENABLE                
  #define EIINT161_ENABLE                 0x00000000u
#endif

// #define EIINT162_ENABLE                 (IRQ_TABLE_START + 0x00000288u)
#ifndef EIINT162_ENABLE                
  #define EIINT162_ENABLE                 0x00000000u
#endif

// #define EIINT163_ENABLE                 (IRQ_TABLE_START + 0x0000028Cu)
#ifndef EIINT163_ENABLE                
  #define EIINT163_ENABLE                 0x00000000u
#endif

// #define EIINT164_ENABLE                 (IRQ_TABLE_START + 0x00000290u)
#ifndef EIINT164_ENABLE                
  #define EIINT164_ENABLE                 0x00000000u
#endif

// #define EIINT165_ENABLE                 (IRQ_TABLE_START + 0x00000294u)
#ifndef EIINT165_ENABLE                
  #define EIINT165_ENABLE                 0x00000000u
#endif

// #define EIINT166_ENABLE                 (IRQ_TABLE_START + 0x00000298u)
#ifndef EIINT166_ENABLE                
  #define EIINT166_ENABLE                 0x00000000u
#endif

// #define EIINT167_ENABLE                 (IRQ_TABLE_START + 0x0000029Cu)
#ifndef EIINT167_ENABLE                
  #define EIINT167_ENABLE                 0x00000000u
#endif

// #define EIINT168_ENABLE                 (IRQ_TABLE_START + 0x000002A0u)
#ifndef EIINT168_ENABLE                
  #define EIINT168_ENABLE                 0x00000000u
#endif

// #define EIINT169_ENABLE                 (IRQ_TABLE_START + 0x000002A4u)
#ifndef EIINT169_ENABLE                
  #define EIINT169_ENABLE                 0x00000000u
#endif

// #define EIINT170_ENABLE                 (IRQ_TABLE_START + 0x000002A8u)
#ifndef EIINT170_ENABLE                
  #define EIINT170_ENABLE                 0x00000000u
#endif

// #define EIINT171_ENABLE                 (IRQ_TABLE_START + 0x000002ACu)
#ifndef EIINT171_ENABLE                
  #define EIINT171_ENABLE                 0x00000000u
#endif

// #define EIINT172_ENABLE                 (IRQ_TABLE_START + 0x000002B0u)
#ifndef EIINT172_ENABLE                
  #define EIINT172_ENABLE                 0x00000000u
#endif

// #define EIINT173_ENABLE                 (IRQ_TABLE_START + 0x000002B4u)
#ifndef EIINT173_ENABLE                
  #define EIINT173_ENABLE                 0x00000000u
#endif

// #define EIINT174_ENABLE                 (IRQ_TABLE_START + 0x000002B8u)
#ifndef EIINT174_ENABLE                
  #define EIINT174_ENABLE                 0x00000000u
#endif

// #define EIINT175_ENABLE                 (IRQ_TABLE_START + 0x000002BCu)
#ifndef EIINT175_ENABLE                
  #define EIINT175_ENABLE                 0x00000000u
#endif

// #define EIINT176_ENABLE                 (IRQ_TABLE_START + 0x000002C0u)
#ifndef EIINT176_ENABLE                
  #define EIINT176_ENABLE                 0x00000000u
#endif

// #define EIINT177_ENABLE                 (IRQ_TABLE_START + 0x000002C4u)
#ifndef EIINT177_ENABLE                
  #define EIINT177_ENABLE                 0x00000000u
#endif

// #define EIINT178_ENABLE                 (IRQ_TABLE_START + 0x000002C8u)
#ifndef EIINT178_ENABLE                
  #define EIINT178_ENABLE                 0x00000000u
#endif

// #define EIINT179_ENABLE                 (IRQ_TABLE_START + 0x000002CCu)
#ifndef EIINT179_ENABLE                
  #define EIINT179_ENABLE                 0x00000000u
#endif

// #define EIINT180_ENABLE                 (IRQ_TABLE_START + 0x000002D0u)
#ifndef EIINT180_ENABLE                
  #define EIINT180_ENABLE                 0x00000000u
#endif

// #define EIINT181_ENABLE                 (IRQ_TABLE_START + 0x000002D4u)
#ifndef EIINT181_ENABLE                
  #define EIINT181_ENABLE                 0x00000000u
#endif

// #define EIINT182_ENABLE                 (IRQ_TABLE_START + 0x000002D8u)
#ifndef EIINT182_ENABLE                
  #define EIINT182_ENABLE                 0x00000000u
#endif

// #define EIINT183_ENABLE                 (IRQ_TABLE_START + 0x000002DCu)
#ifndef EIINT183_ENABLE                
  #define EIINT183_ENABLE                 0x00000000u
#endif

// #define EIINT184_ENABLE                 (IRQ_TABLE_START + 0x000002E0u)
#ifndef EIINT184_ENABLE                
  #define EIINT184_ENABLE                 0x00000000u
#endif

// #define EIINT185_ENABLE                 (IRQ_TABLE_START + 0x000002E4u)
#ifndef EIINT185_ENABLE                
  #define EIINT185_ENABLE                 0x00000000u
#endif

// #define EIINT186_ENABLE                 (IRQ_TABLE_START + 0x000002E8u)
#ifndef EIINT186_ENABLE                
  #define EIINT186_ENABLE                 0x00000000u
#endif

// #define EIINT187_ENABLE                 (IRQ_TABLE_START + 0x000002ECu)
#ifndef EIINT187_ENABLE                
  #define EIINT187_ENABLE                 0x00000000u
#endif

// #define EIINT188_ENABLE                 (IRQ_TABLE_START + 0x000002F0u)
#ifndef EIINT188_ENABLE                
  #define EIINT188_ENABLE                 0x00000000u
#endif

// #define EIINT189_ENABLE                 (IRQ_TABLE_START + 0x000002F4u)
#ifndef EIINT189_ENABLE                
  #define EIINT189_ENABLE                 0x00000000u
#endif

// #define EIINT190_ENABLE                 (IRQ_TABLE_START + 0x000002F8u)
#ifndef EIINT190_ENABLE                
  #define EIINT190_ENABLE                 0x00000000u
#endif

// #define EIINT191_ENABLE                 (IRQ_TABLE_START + 0x000002FCu)
#ifndef EIINT191_ENABLE                
  #define EIINT191_ENABLE                 0x00000000u
#endif

// #define EIINT192_ENABLE                 (IRQ_TABLE_START + 0x00000300u)
#ifndef EIINT192_ENABLE                
  #define EIINT192_ENABLE                 0x00000000u
#endif

// #define EIINT193_ENABLE                 (IRQ_TABLE_START + 0x00000304u)
#ifndef EIINT193_ENABLE                
  #define EIINT193_ENABLE                 0x00000000u
#endif

// #define EIINT194_ENABLE                 (IRQ_TABLE_START + 0x00000308u)
#ifndef EIINT194_ENABLE                
  #define EIINT194_ENABLE                 0x00000000u
#endif

// #define EIINT195_ENABLE                 (IRQ_TABLE_START + 0x0000030Cu)
#ifndef EIINT195_ENABLE                
  #define EIINT195_ENABLE                 0x00000000u
#endif

// #define EIINT196_ENABLE                 (IRQ_TABLE_START + 0x00000310u)
#ifndef EIINT196_ENABLE                
  #define EIINT196_ENABLE                 0x00000000u
#endif

// #define EIINT197_ENABLE                 (IRQ_TABLE_START + 0x00000314u)
#ifndef EIINT197_ENABLE                
  #define EIINT197_ENABLE                 0x00000000u
#endif

// #define EIINT198_ENABLE                 (IRQ_TABLE_START + 0x00000318u)
#ifndef EIINT198_ENABLE                
  #define EIINT198_ENABLE                 0x00000000u
#endif

// #define EIINT199_ENABLE                 (IRQ_TABLE_START + 0x0000031Cu)
#ifndef EIINT199_ENABLE                
  #define EIINT199_ENABLE                 0x00000000u
#endif

// #define EIINT200_ENABLE                 (IRQ_TABLE_START + 0x00000320u)
#ifndef EIINT200_ENABLE                
  #define EIINT200_ENABLE                 0x00000000u
#endif

// #define EIINT201_ENABLE                 (IRQ_TABLE_START + 0x00000324u)
#ifndef EIINT201_ENABLE                
  #define EIINT201_ENABLE                 0x00000000u
#endif

// #define EIINT202_ENABLE                 (IRQ_TABLE_START + 0x00000328u)
#ifndef EIINT202_ENABLE                
  #define EIINT202_ENABLE                 0x00000000u
#endif

// #define EIINT203_ENABLE                 (IRQ_TABLE_START + 0x0000032Cu)
#ifndef EIINT203_ENABLE                
  #define EIINT203_ENABLE                 0x00000000u
#endif

// #define EIINT204_ENABLE                 (IRQ_TABLE_START + 0x00000330u)
#ifndef EIINT204_ENABLE                
  #define EIINT204_ENABLE                 0x00000000u
#endif

// #define EIINT205_ENABLE                 (IRQ_TABLE_START + 0x00000334u)
#ifndef EIINT205_ENABLE                
  #define EIINT205_ENABLE                 0x00000000u
#endif

// #define EIINT206_ENABLE                 (IRQ_TABLE_START + 0x00000338u)
#ifndef EIINT206_ENABLE                
  #define EIINT206_ENABLE                 0x00000000u
#endif

// #define EIINT207_ENABLE                 (IRQ_TABLE_START + 0x0000033Cu)
#ifndef EIINT207_ENABLE                
  #define EIINT207_ENABLE                 0x00000000u
#endif

// #define EIINT208_ENABLE                 (IRQ_TABLE_START + 0x00000340u)
#ifndef EIINT208_ENABLE                
  #define EIINT208_ENABLE                 0x00000000u
#endif

// #define EIINT209_ENABLE                 (IRQ_TABLE_START + 0x00000344u)
#ifndef EIINT209_ENABLE                
  #define EIINT209_ENABLE                 0x00000000u
#endif

// #define EIINT210_ENABLE                 (IRQ_TABLE_START + 0x00000348u)
#ifndef EIINT210_ENABLE                
  #define EIINT210_ENABLE                 0x00000000u
#endif

// #define EIINT211_ENABLE                 (IRQ_TABLE_START + 0x0000034Cu)
#ifndef EIINT211_ENABLE                
  #define EIINT211_ENABLE                 0x00000000u
#endif

// #define EIINT212_ENABLE                 (IRQ_TABLE_START + 0x00000350u)
#ifndef EIINT212_ENABLE                
  #define EIINT212_ENABLE                 0x00000000u
#endif

// #define EIINT213_ENABLE                 (IRQ_TABLE_START + 0x00000354u)
#ifndef EIINT213_ENABLE                
  #define EIINT213_ENABLE                 0x00000000u
#endif

// #define EIINT214_ENABLE                 (IRQ_TABLE_START + 0x00000358u)
#ifndef EIINT214_ENABLE                
  #define EIINT214_ENABLE                 0x00000000u
#endif

// #define EIINT215_ENABLE                 (IRQ_TABLE_START + 0x0000035Cu)
#ifndef EIINT215_ENABLE                
  #define EIINT215_ENABLE                 0x00000000u
#endif

// #define EIINT216_ENABLE                 (IRQ_TABLE_START + 0x00000360u)
#ifndef EIINT216_ENABLE                
  #define EIINT216_ENABLE                 0x00000000u
#endif

// #define EIINT217_ENABLE                 (IRQ_TABLE_START + 0x00000364u)
#ifndef EIINT217_ENABLE                
  #define EIINT217_ENABLE                 0x00000000u
#endif

// #define EIINT218_ENABLE                 (IRQ_TABLE_START + 0x00000368u)
#ifndef EIINT218_ENABLE                
  #define EIINT218_ENABLE                 0x00000000u
#endif

// #define EIINT219_ENABLE                 (IRQ_TABLE_START + 0x0000036Cu)
#ifndef EIINT219_ENABLE                
  #define EIINT219_ENABLE                 0x00000000u
#endif

// #define EIINT220_ENABLE                 (IRQ_TABLE_START + 0x00000370u)
#ifndef EIINT220_ENABLE                
  #define EIINT220_ENABLE                 0x00000000u
#endif

// #define EIINT221_ENABLE                 (IRQ_TABLE_START + 0x00000374u)
#ifndef EIINT221_ENABLE                
  #define EIINT221_ENABLE                 0x00000000u
#endif

// #define EIINT222_ENABLE                 (IRQ_TABLE_START + 0x00000378u)
#ifndef EIINT222_ENABLE                
  #define EIINT222_ENABLE                 0x00000000u
#endif

// #define EIINT223_ENABLE                 (IRQ_TABLE_START + 0x0000037Cu)
#ifndef EIINT223_ENABLE                
  #define EIINT223_ENABLE                 0x00000000u
#endif

// #define EIINT224_ENABLE                 (IRQ_TABLE_START + 0x00000380u)
#ifndef EIINT224_ENABLE                
  #define EIINT224_ENABLE                 0x00000000u
#endif

// #define EIINT225_ENABLE                 (IRQ_TABLE_START + 0x00000384u)
#ifndef EIINT225_ENABLE                
  #define EIINT225_ENABLE                 0x00000000u
#endif

// #define EIINT226_ENABLE                 (IRQ_TABLE_START + 0x00000388u)
#ifndef EIINT226_ENABLE                
  #define EIINT226_ENABLE                 0x00000000u
#endif

// #define EIINT227_ENABLE                 (IRQ_TABLE_START + 0x0000038Cu)
#ifndef EIINT227_ENABLE                
  #define EIINT227_ENABLE                 0x00000000u
#endif

// #define EIINT228_ENABLE                 (IRQ_TABLE_START + 0x00000390u)
#ifndef EIINT228_ENABLE                
  #define EIINT228_ENABLE                 0x00000000u
#endif

// #define EIINT229_ENABLE                 (IRQ_TABLE_START + 0x00000394u)
#ifndef EIINT229_ENABLE                
  #define EIINT229_ENABLE                 0x00000000u
#endif

// #define EIINT230_ENABLE                 (IRQ_TABLE_START + 0x00000398u)
#ifndef EIINT230_ENABLE                
  #define EIINT230_ENABLE                 0x00000000u
#endif

// #define EIINT231_ENABLE                 (IRQ_TABLE_START + 0x0000039Cu)
#ifndef EIINT231_ENABLE                
  #define EIINT231_ENABLE                 0x00000000u
#endif

// #define EIINT232_ENABLE                 (IRQ_TABLE_START + 0x000003A0u)
#ifndef EIINT232_ENABLE                
  #define EIINT232_ENABLE                 0x00000000u
#endif

// #define EIINT233_ENABLE                 (IRQ_TABLE_START + 0x000003A4u)
#ifndef EIINT233_ENABLE                
  #define EIINT233_ENABLE                 0x00000000u
#endif

// #define EIINT234_ENABLE                 (IRQ_TABLE_START + 0x000003A8u)
#ifndef EIINT234_ENABLE                
  #define EIINT234_ENABLE                 0x00000000u
#endif

// #define EIINT235_ENABLE                 (IRQ_TABLE_START + 0x000003ACu)
#ifndef EIINT235_ENABLE                
  #define EIINT235_ENABLE                 0x00000000u
#endif

// #define EIINT236_ENABLE                 (IRQ_TABLE_START + 0x000003B0u)
#ifndef EIINT236_ENABLE                
  #define EIINT236_ENABLE                 0x00000000u
#endif

// #define EIINT237_ENABLE                 (IRQ_TABLE_START + 0x000003B4u)
#ifndef EIINT237_ENABLE                
  #define EIINT237_ENABLE                 0x00000000u
#endif

// #define EIINT238_ENABLE                 (IRQ_TABLE_START + 0x000003B8u)
#ifndef EIINT238_ENABLE                
  #define EIINT238_ENABLE                 0x00000000u
#endif

// #define EIINT239_ENABLE                 (IRQ_TABLE_START + 0x000003BCu)
#ifndef EIINT239_ENABLE                
  #define EIINT239_ENABLE                 0x00000000u
#endif

// #define EIINT240_ENABLE                 (IRQ_TABLE_START + 0x000003C0u)
#ifndef EIINT240_ENABLE                
  #define EIINT240_ENABLE                 0x00000000u
#endif

// #define EIINT241_ENABLE                 (IRQ_TABLE_START + 0x000003C4u)
#ifndef EIINT241_ENABLE                
  #define EIINT241_ENABLE                 0x00000000u
#endif

// #define EIINT242_ENABLE                 (IRQ_TABLE_START + 0x000003C8u)
#ifndef EIINT242_ENABLE                
  #define EIINT242_ENABLE                 0x00000000u
#endif

// #define EIINT243_ENABLE                 (IRQ_TABLE_START + 0x000003CCu)
#ifndef EIINT243_ENABLE                
  #define EIINT243_ENABLE                 0x00000000u
#endif

// #define EIINT244_ENABLE                 (IRQ_TABLE_START + 0x000003D0u)
#ifndef EIINT244_ENABLE                
  #define EIINT244_ENABLE                 0x00000000u
#endif

// #define EIINT245_ENABLE                 (IRQ_TABLE_START + 0x000003D4u)
#ifndef EIINT245_ENABLE                
  #define EIINT245_ENABLE                 0x00000000u
#endif

// #define EIINT246_ENABLE                 (IRQ_TABLE_START + 0x000003D8u)
#ifndef EIINT246_ENABLE                
  #define EIINT246_ENABLE                 0x00000000u
#endif

// #define EIINT247_ENABLE                 (IRQ_TABLE_START + 0x000003DCu)
#ifndef EIINT247_ENABLE                
  #define EIINT247_ENABLE                 0x00000000u
#endif

// #define EIINT248_ENABLE                 (IRQ_TABLE_START + 0x000003E0u)
#ifndef EIINT248_ENABLE                
  #define EIINT248_ENABLE                 0x00000000u
#endif

// #define EIINT249_ENABLE                 (IRQ_TABLE_START + 0x000003E4u)
#ifndef EIINT249_ENABLE                
  #define EIINT249_ENABLE                 0x00000000u
#endif

// #define EIINT250_ENABLE                 (IRQ_TABLE_START + 0x000003E8u)
#ifndef EIINT250_ENABLE                
  #define EIINT250_ENABLE                 0x00000000u
#endif

// #define EIINT251_ENABLE                 (IRQ_TABLE_START + 0x000003ECu)
#ifndef EIINT251_ENABLE                
  #define EIINT251_ENABLE                 0x00000000u
#endif

// #define EIINT252_ENABLE                 (IRQ_TABLE_START + 0x000003F0u)
#ifndef EIINT252_ENABLE                
  #define EIINT252_ENABLE                 0x00000000u
#endif

// #define EIINT253_ENABLE                 (IRQ_TABLE_START + 0x000003F4u)
#ifndef EIINT253_ENABLE                
  #define EIINT253_ENABLE                 0x00000000u
#endif

// #define EIINT254_ENABLE                 (IRQ_TABLE_START + 0x000003F8u)
#ifndef EIINT254_ENABLE                
  #define EIINT254_ENABLE                 0x00000000u
#endif

// #define EIINT255_ENABLE                 (IRQ_TABLE_START + 0x000003FCu)
#ifndef EIINT255_ENABLE                
  #define EIINT255_ENABLE                 0x00000000u
#endif

// #define EIINT256_ENABLE                 (IRQ_TABLE_START + 0x00000400u)
#ifndef EIINT256_ENABLE                
  #define EIINT256_ENABLE                 0x00000000u
#endif

// #define EIINT257_ENABLE                 (IRQ_TABLE_START + 0x00000404u)
#ifndef EIINT257_ENABLE                
  #define EIINT257_ENABLE                 0x00000000u
#endif

// #define EIINT258_ENABLE                 (IRQ_TABLE_START + 0x00000408u)
#ifndef EIINT258_ENABLE                
  #define EIINT258_ENABLE                 0x00000000u
#endif

// #define EIINT259_ENABLE                 (IRQ_TABLE_START + 0x0000040Cu)
#ifndef EIINT259_ENABLE                
  #define EIINT259_ENABLE                 0x00000000u
#endif

// #define EIINT260_ENABLE                 (IRQ_TABLE_START + 0x00000410u)
#ifndef EIINT260_ENABLE                
  #define EIINT260_ENABLE                 0x00000000u
#endif

// #define EIINT261_ENABLE                 (IRQ_TABLE_START + 0x00000414u)
#ifndef EIINT261_ENABLE                
  #define EIINT261_ENABLE                 0x00000000u
#endif

// #define EIINT262_ENABLE                 (IRQ_TABLE_START + 0x00000418u)
#ifndef EIINT262_ENABLE                
  #define EIINT262_ENABLE                 0x00000000u
#endif

// #define EIINT263_ENABLE                 (IRQ_TABLE_START + 0x0000041Cu)
#ifndef EIINT263_ENABLE                
  #define EIINT263_ENABLE                 0x00000000u
#endif

// #define EIINT264_ENABLE                 (IRQ_TABLE_START + 0x00000420u)
#ifndef EIINT264_ENABLE                
  #define EIINT264_ENABLE                 0x00000000u
#endif

// #define EIINT265_ENABLE                 (IRQ_TABLE_START + 0x00000424u)
#ifndef EIINT265_ENABLE                
  #define EIINT265_ENABLE                 0x00000000u
#endif

// #define EIINT266_ENABLE                 (IRQ_TABLE_START + 0x00000428u)
#ifndef EIINT266_ENABLE                
  #define EIINT266_ENABLE                 0x00000000u
#endif

// #define EIINT267_ENABLE                 (IRQ_TABLE_START + 0x0000042Cu)
#ifndef EIINT267_ENABLE                
  #define EIINT267_ENABLE                 0x00000000u
#endif

// #define EIINT268_ENABLE                 (IRQ_TABLE_START + 0x00000430u)
#ifndef EIINT268_ENABLE                
  #define EIINT268_ENABLE                 0x00000000u
#endif

// #define EIINT269_ENABLE                 (IRQ_TABLE_START + 0x00000434u)
#ifndef EIINT269_ENABLE                
  #define EIINT269_ENABLE                 0x00000000u
#endif

// #define EIINT270_ENABLE                 (IRQ_TABLE_START + 0x00000438u)
#ifndef EIINT270_ENABLE                
  #define EIINT270_ENABLE                 0x00000000u
#endif

// #define EIINT271_ENABLE                 (IRQ_TABLE_START + 0x0000043Cu)
#ifndef EIINT271_ENABLE                
  #define EIINT271_ENABLE                 0x00000000u
#endif

// #define EIINT272_ENABLE                 (IRQ_TABLE_START + 0x00000440u)
#ifndef EIINT272_ENABLE                
  #define EIINT272_ENABLE                 0x00000000u
#endif

// #define EIINT273_ENABLE                 (IRQ_TABLE_START + 0x00000444u)
#ifndef EIINT273_ENABLE                
  #define EIINT273_ENABLE                 0x00000000u
#endif

// #define EIINT274_ENABLE                 (IRQ_TABLE_START + 0x00000448u)
#ifndef EIINT274_ENABLE                
  #define EIINT274_ENABLE                 0x00000000u
#endif

// #define EIINT275_ENABLE                 (IRQ_TABLE_START + 0x0000044Cu)
#ifndef EIINT275_ENABLE                
  #define EIINT275_ENABLE                 0x00000000u
#endif

// #define EIINT276_ENABLE                 (IRQ_TABLE_START + 0x00000450u)
#ifndef EIINT276_ENABLE                
  #define EIINT276_ENABLE                 0x00000000u
#endif

// #define EIINT277_ENABLE                 (IRQ_TABLE_START + 0x00000454u)
#ifndef EIINT277_ENABLE                
  #define EIINT277_ENABLE                 0x00000000u
#endif

// #define EIINT278_ENABLE                 (IRQ_TABLE_START + 0x00000458u)
#ifndef EIINT278_ENABLE                
  #define EIINT278_ENABLE                 0x00000000u
#endif

// #define EIINT279_ENABLE                 (IRQ_TABLE_START + 0x0000045Cu)
#ifndef EIINT279_ENABLE                
  #define EIINT279_ENABLE                 0x00000000u
#endif

// #define EIINT280_ENABLE                 (IRQ_TABLE_START + 0x00000460u)
#ifndef EIINT280_ENABLE                
  #define EIINT280_ENABLE                 0x00000000u
#endif

// #define EIINT281_ENABLE                 (IRQ_TABLE_START + 0x00000464u)
#ifndef EIINT281_ENABLE                
  #define EIINT281_ENABLE                 0x00000000u
#endif

// #define EIINT282_ENABLE                 (IRQ_TABLE_START + 0x00000468u)
#ifndef EIINT282_ENABLE                
  #define EIINT282_ENABLE                 0x00000000u
#endif

// #define EIINT283_ENABLE                 (IRQ_TABLE_START + 0x0000046Cu)
#ifndef EIINT283_ENABLE                
  #define EIINT283_ENABLE                 0x00000000u
#endif

// #define EIINT284_ENABLE                 (IRQ_TABLE_START + 0x00000470u)
#ifndef EIINT284_ENABLE                
  #define EIINT284_ENABLE                 0x00000000u
#endif

// #define EIINT285_ENABLE                 (IRQ_TABLE_START + 0x00000474u)
#ifndef EIINT285_ENABLE                
  #define EIINT285_ENABLE                 0x00000000u
#endif

// #define EIINT286_ENABLE                 (IRQ_TABLE_START + 0x00000478u)
#ifndef EIINT286_ENABLE                
  #define EIINT286_ENABLE                 0x00000000u
#endif

// #define EIINT287_ENABLE                 (IRQ_TABLE_START + 0x0000047Cu)
#ifndef EIINT287_ENABLE                
  #define EIINT287_ENABLE                 0x00000000u
#endif

// #define EIINT288_ENABLE                 (IRQ_TABLE_START + 0x00000480u)
#ifndef EIINT288_ENABLE                
  #define EIINT288_ENABLE                 0x00000000u
#endif

// #define EIINT289_ENABLE                 (IRQ_TABLE_START + 0x00000484u)
#ifndef EIINT289_ENABLE                
  #define EIINT289_ENABLE                 0x00000000u
#endif

// #define EIINT290_ENABLE                 (IRQ_TABLE_START + 0x00000488u)
#ifndef EIINT290_ENABLE                
  #define EIINT290_ENABLE                 0x00000000u
#endif

// #define EIINT291_ENABLE                 (IRQ_TABLE_START + 0x0000048Cu)
#ifndef EIINT291_ENABLE                
  #define EIINT291_ENABLE                 0x00000000u
#endif

// #define EIINT292_ENABLE                 (IRQ_TABLE_START + 0x00000490u)
#ifndef EIINT292_ENABLE                
  #define EIINT292_ENABLE                 0x00000000u
#endif

// #define EIINT293_ENABLE                 (IRQ_TABLE_START + 0x00000494u)
#ifndef EIINT293_ENABLE                
  #define EIINT293_ENABLE                 0x00000000u
#endif

// #define EIINT294_ENABLE                 (IRQ_TABLE_START + 0x00000498u)
#ifndef EIINT294_ENABLE                
  #define EIINT294_ENABLE                 0x00000000u
#endif

// #define EIINT295_ENABLE                 (IRQ_TABLE_START + 0x0000049Cu)
#ifndef EIINT295_ENABLE                
  #define EIINT295_ENABLE                 0x00000000u
#endif

// #define EIINT296_ENABLE                 (IRQ_TABLE_START + 0x000004A0u)
#ifndef EIINT296_ENABLE                
  #define EIINT296_ENABLE                 0x00000000u
#endif

// #define EIINT297_ENABLE                 (IRQ_TABLE_START + 0x000004A4u)
#ifndef EIINT297_ENABLE                
  #define EIINT297_ENABLE                 0x00000000u
#endif

// #define EIINT298_ENABLE                 (IRQ_TABLE_START + 0x000004A8u)
#ifndef EIINT298_ENABLE                
  #define EIINT298_ENABLE                 0x00000000u
#endif

// #define EIINT299_ENABLE                 (IRQ_TABLE_START + 0x000004ACu)
#ifndef EIINT299_ENABLE                
  #define EIINT299_ENABLE                 0x00000000u
#endif

// #define EIINT300_ENABLE                 (IRQ_TABLE_START + 0x000004B0u)
#ifndef EIINT300_ENABLE                
  #define EIINT300_ENABLE                 0x00000000u
#endif

// #define EIINT301_ENABLE                 (IRQ_TABLE_START + 0x000004B4u)
#ifndef EIINT301_ENABLE                
  #define EIINT301_ENABLE                 0x00000000u
#endif

// #define EIINT302_ENABLE                 (IRQ_TABLE_START + 0x000004B8u)
#ifndef EIINT302_ENABLE                
  #define EIINT302_ENABLE                 0x00000000u
#endif

// #define EIINT303_ENABLE                 (IRQ_TABLE_START + 0x000004BCu)
#ifndef EIINT303_ENABLE                
  #define EIINT303_ENABLE                 0x00000000u
#endif

// #define EIINT304_ENABLE                 (IRQ_TABLE_START + 0x000004C0u)
#ifndef EIINT304_ENABLE                
  #define EIINT304_ENABLE                 0x00000000u
#endif

// #define EIINT305_ENABLE                 (IRQ_TABLE_START + 0x000004C4u)
#ifndef EIINT305_ENABLE                
  #define EIINT305_ENABLE                 0x00000000u
#endif

// #define EIINT306_ENABLE                 (IRQ_TABLE_START + 0x000004C8u)
#ifndef EIINT306_ENABLE                
  #define EIINT306_ENABLE                 0x00000000u
#endif

// #define EIINT307_ENABLE                 (IRQ_TABLE_START + 0x000004CCu)
#ifndef EIINT307_ENABLE                
  #define EIINT307_ENABLE                 0x00000000u
#endif

// #define EIINT308_ENABLE                 (IRQ_TABLE_START + 0x000004D0u)
#ifndef EIINT308_ENABLE                
  #define EIINT308_ENABLE                 0x00000000u
#endif

// #define EIINT309_ENABLE                 (IRQ_TABLE_START + 0x000004D4u)
#ifndef EIINT309_ENABLE                
  #define EIINT309_ENABLE                 0x00000000u
#endif

// #define EIINT310_ENABLE                 (IRQ_TABLE_START + 0x000004D8u)
#ifndef EIINT310_ENABLE                
  #define EIINT310_ENABLE                 0x00000000u
#endif

// #define EIINT311_ENABLE                 (IRQ_TABLE_START + 0x000004DCu)
#ifndef EIINT311_ENABLE                
  #define EIINT311_ENABLE                 0x00000000u
#endif

// #define EIINT312_ENABLE                 (IRQ_TABLE_START + 0x000004E0u)
#ifndef EIINT312_ENABLE                
  #define EIINT312_ENABLE                 0x00000000u
#endif

// #define EIINT313_ENABLE                 (IRQ_TABLE_START + 0x000004E4u)
#ifndef EIINT313_ENABLE                
  #define EIINT313_ENABLE                 0x00000000u
#endif

// #define EIINT314_ENABLE                 (IRQ_TABLE_START + 0x000004E8u)
#ifndef EIINT314_ENABLE                
  #define EIINT314_ENABLE                 0x00000000u
#endif

// #define EIINT315_ENABLE                 (IRQ_TABLE_START + 0x000004ECu)
#ifndef EIINT315_ENABLE                
  #define EIINT315_ENABLE                 0x00000000u
#endif

// #define EIINT316_ENABLE                 (IRQ_TABLE_START + 0x000004F0u)
#ifndef EIINT316_ENABLE                
  #define EIINT316_ENABLE                 0x00000000u
#endif

// #define EIINT317_ENABLE                 (IRQ_TABLE_START + 0x000004F4u)
#ifndef EIINT317_ENABLE                
  #define EIINT317_ENABLE                 0x00000000u
#endif

// #define EIINT318_ENABLE                 (IRQ_TABLE_START + 0x000004F8u)
#ifndef EIINT318_ENABLE                
  #define EIINT318_ENABLE                 0x00000000u
#endif

// #define EIINT319_ENABLE                 (IRQ_TABLE_START + 0x000004FCu)
#ifndef EIINT319_ENABLE                
  #define EIINT319_ENABLE                 0x00000000u
#endif

// #define EIINT320_ENABLE                 (IRQ_TABLE_START + 0x00000500u)
#ifndef EIINT320_ENABLE                
  #define EIINT320_ENABLE                 0x00000000u
#endif

// #define EIINT321_ENABLE                 (IRQ_TABLE_START + 0x00000504u)
#ifndef EIINT321_ENABLE                
  #define EIINT321_ENABLE                 0x00000000u
#endif

// #define EIINT322_ENABLE                 (IRQ_TABLE_START + 0x00000508u)
#ifndef EIINT322_ENABLE                
  #define EIINT322_ENABLE                 0x00000000u
#endif

// #define EIINT323_ENABLE                 (IRQ_TABLE_START + 0x0000050Cu)
#ifndef EIINT323_ENABLE                
  #define EIINT323_ENABLE                 0x00000000u
#endif

// #define EIINT324_ENABLE                 (IRQ_TABLE_START + 0x00000510u)
#ifndef EIINT324_ENABLE                
  #define EIINT324_ENABLE                 0x00000000u
#endif

// #define EIINT325_ENABLE                 (IRQ_TABLE_START + 0x00000514u)
#ifndef EIINT325_ENABLE                
  #define EIINT325_ENABLE                 0x00000000u
#endif

// #define EIINT326_ENABLE                 (IRQ_TABLE_START + 0x00000518u)
#ifndef EIINT326_ENABLE                
  #define EIINT326_ENABLE                 0x00000000u
#endif

// #define EIINT327_ENABLE                 (IRQ_TABLE_START + 0x0000051Cu)
#ifndef EIINT327_ENABLE                
  #define EIINT327_ENABLE                 0x00000000u
#endif

// #define EIINT328_ENABLE                 (IRQ_TABLE_START + 0x00000520u)
#ifndef EIINT328_ENABLE                
  #define EIINT328_ENABLE                 0x00000000u
#endif

// #define EIINT329_ENABLE                 (IRQ_TABLE_START + 0x00000524u)
#ifndef EIINT329_ENABLE                
  #define EIINT329_ENABLE                 0x00000000u
#endif

// #define EIINT330_ENABLE                 (IRQ_TABLE_START + 0x00000528u)
#ifndef EIINT330_ENABLE                
  #define EIINT330_ENABLE                 0x00000000u
#endif

// #define EIINT331_ENABLE                 (IRQ_TABLE_START + 0x0000052Cu)
#ifndef EIINT331_ENABLE                
  #define EIINT331_ENABLE                 0x00000000u
#endif

// #define EIINT332_ENABLE                 (IRQ_TABLE_START + 0x00000530u)
#ifndef EIINT332_ENABLE                
  #define EIINT332_ENABLE                 0x00000000u
#endif

// #define EIINT333_ENABLE                 (IRQ_TABLE_START + 0x00000534u)
#ifndef EIINT333_ENABLE                
  #define EIINT333_ENABLE                 0x00000000u
#endif

// #define EIINT334_ENABLE                 (IRQ_TABLE_START + 0x00000538u)
#ifndef EIINT334_ENABLE                
  #define EIINT334_ENABLE                 0x00000000u
#endif

// #define EIINT335_ENABLE                 (IRQ_TABLE_START + 0x0000053Cu)
#ifndef EIINT335_ENABLE                
  #define EIINT335_ENABLE                 0x00000000u
#endif

// #define EIINT336_ENABLE                 (IRQ_TABLE_START + 0x00000540u)
#ifndef EIINT336_ENABLE                
  #define EIINT336_ENABLE                 0x00000000u
#endif

// #define EIINT337_ENABLE                 (IRQ_TABLE_START + 0x00000544u)
#ifndef EIINT337_ENABLE                
  #define EIINT337_ENABLE                 0x00000000u
#endif

// #define EIINT338_ENABLE                 (IRQ_TABLE_START + 0x00000548u)
#ifndef EIINT338_ENABLE                
  #define EIINT338_ENABLE                 0x00000000u
#endif

// #define EIINT339_ENABLE                 (IRQ_TABLE_START + 0x0000054Cu)
#ifndef EIINT339_ENABLE                
  #define EIINT339_ENABLE                 0x00000000u
#endif

// #define EIINT340_ENABLE                 (IRQ_TABLE_START + 0x00000550u)
#ifndef EIINT340_ENABLE                
  #define EIINT340_ENABLE                 0x00000000u
#endif

// #define EIINT341_ENABLE                 (IRQ_TABLE_START + 0x00000554u)
#ifndef EIINT341_ENABLE                
  #define EIINT341_ENABLE                 0x00000000u
#endif

// #define EIINT342_ENABLE                 (IRQ_TABLE_START + 0x00000558u)
#ifndef EIINT342_ENABLE                
  #define EIINT342_ENABLE                 0x00000000u
#endif

// #define EIINT343_ENABLE                 (IRQ_TABLE_START + 0x0000055Cu)
#ifndef EIINT343_ENABLE                
  #define EIINT343_ENABLE                 0x00000000u
#endif

// #define EIINT344_ENABLE                 (IRQ_TABLE_START + 0x00000560u)
#ifndef EIINT344_ENABLE                
  #define EIINT344_ENABLE                 0x00000000u
#endif

// #define EIINT345_ENABLE                 (IRQ_TABLE_START + 0x00000564u)
#ifndef EIINT345_ENABLE                
  #define EIINT345_ENABLE                 0x00000000u
#endif

// #define EIINT346_ENABLE                 (IRQ_TABLE_START + 0x00000568u)
#ifndef EIINT346_ENABLE                
  #define EIINT346_ENABLE                 0x00000000u
#endif

// #define EIINT347_ENABLE                 (IRQ_TABLE_START + 0x0000056Cu)
#ifndef EIINT347_ENABLE                
  #define EIINT347_ENABLE                 0x00000000u
#endif

// #define EIINT348_ENABLE                 (IRQ_TABLE_START + 0x00000570u)
#ifndef EIINT348_ENABLE                
  #define EIINT348_ENABLE                 0x00000000u
#endif

// #define EIINT349_ENABLE                 (IRQ_TABLE_START + 0x00000574u)
#ifndef EIINT349_ENABLE                
  #define EIINT349_ENABLE                 0x00000000u
#endif

// #define EIINT350_ENABLE                 (IRQ_TABLE_START + 0x00000578u)
#ifndef EIINT350_ENABLE                
  #define EIINT350_ENABLE                 0x00000000u
#endif

// #define EIINT351_ENABLE                 (IRQ_TABLE_START + 0x0000057Cu)
#ifndef EIINT351_ENABLE                
  #define EIINT351_ENABLE                 0x00000000u
#endif

// #define EIINT352_ENABLE                 (IRQ_TABLE_START + 0x00000580u)
#ifndef EIINT352_ENABLE                
  #define EIINT352_ENABLE                 0x00000000u
#endif

// #define EIINT353_ENABLE                 (IRQ_TABLE_START + 0x00000584u)
#ifndef EIINT353_ENABLE                
  #define EIINT353_ENABLE                 0x00000000u
#endif

// #define EIINT354_ENABLE                 (IRQ_TABLE_START + 0x00000588u)
#ifndef EIINT354_ENABLE                
  #define EIINT354_ENABLE                 0x00000000u
#endif

// #define EIINT355_ENABLE                 (IRQ_TABLE_START + 0x0000058Cu)
#ifndef EIINT355_ENABLE                
  #define EIINT355_ENABLE                 0x00000000u
#endif

// #define EIINT356_ENABLE                 (IRQ_TABLE_START + 0x00000590u)
#ifndef EIINT356_ENABLE                
  #define EIINT356_ENABLE                 0x00000000u
#endif

// #define EIINT357_ENABLE                 (IRQ_TABLE_START + 0x00000594u)
#ifndef EIINT357_ENABLE                
  #define EIINT357_ENABLE                 0x00000000u
#endif

// #define EIINT358_ENABLE                 (IRQ_TABLE_START + 0x00000598u)
#ifndef EIINT358_ENABLE                
  #define EIINT358_ENABLE                 0x00000000u
#endif

// #define EIINT359_ENABLE                 (IRQ_TABLE_START + 0x0000059Cu)
#ifndef EIINT359_ENABLE                
  #define EIINT359_ENABLE                 0x00000000u
#endif

// #define EIINT360_ENABLE                 (IRQ_TABLE_START + 0x000005A0u)
#ifndef EIINT360_ENABLE                
  #define EIINT360_ENABLE                 0x00000000u
#endif

// #define EIINT361_ENABLE                 (IRQ_TABLE_START + 0x000005A4u)
#ifndef EIINT361_ENABLE                
  #define EIINT361_ENABLE                 0x00000000u
#endif

// #define EIINT362_ENABLE                 (IRQ_TABLE_START + 0x000005A8u)
#ifndef EIINT362_ENABLE                
  #define EIINT362_ENABLE                 0x00000000u
#endif

// #define EIINT363_ENABLE                 (IRQ_TABLE_START + 0x000005ACu)
#ifndef EIINT363_ENABLE                
  #define EIINT363_ENABLE                 0x00000000u
#endif

// #define EIINT364_ENABLE                 (IRQ_TABLE_START + 0x000005B0u)
#ifndef EIINT364_ENABLE                
  #define EIINT364_ENABLE                 0x00000000u
#endif

// #define EIINT365_ENABLE                 (IRQ_TABLE_START + 0x000005B4u)
#ifndef EIINT365_ENABLE                
  #define EIINT365_ENABLE                 0x00000000u
#endif

// #define EIINT366_ENABLE                 (IRQ_TABLE_START + 0x000005B8u)
#ifndef EIINT366_ENABLE                
  #define EIINT366_ENABLE                 0x00000000u
#endif

// #define EIINT367_ENABLE                 (IRQ_TABLE_START + 0x000005BCu)
#ifndef EIINT367_ENABLE                
  #define EIINT367_ENABLE                 0x00000000u
#endif

// #define EIINT368_ENABLE                 (IRQ_TABLE_START + 0x000005C0u)
#ifndef EIINT368_ENABLE                
  #define EIINT368_ENABLE                 0x00000000u
#endif

// #define EIINT369_ENABLE                 (IRQ_TABLE_START + 0x000005C4u)
#ifndef EIINT369_ENABLE                
  #define EIINT369_ENABLE                 0x00000000u
#endif

// #define EIINT370_ENABLE                 (IRQ_TABLE_START + 0x000005C8u)
#ifndef EIINT370_ENABLE                
  #define EIINT370_ENABLE                 0x00000000u
#endif

// #define EIINT371_ENABLE                 (IRQ_TABLE_START + 0x000005CCu)
#ifndef EIINT371_ENABLE                
  #define EIINT371_ENABLE                 0x00000000u
#endif

// #define EIINT372_ENABLE                 (IRQ_TABLE_START + 0x000005D0u)
#ifndef EIINT372_ENABLE                
  #define EIINT372_ENABLE                 0x00000000u
#endif

// #define EIINT373_ENABLE                 (IRQ_TABLE_START + 0x000005D4u)
#ifndef EIINT373_ENABLE                
  #define EIINT373_ENABLE                 0x00000000u
#endif

// #define EIINT374_ENABLE                 (IRQ_TABLE_START + 0x000005D8u)
#ifndef EIINT374_ENABLE                
  #define EIINT374_ENABLE                 0x00000000u
#endif

// #define EIINT375_ENABLE                 (IRQ_TABLE_START + 0x000005DCu)
#ifndef EIINT375_ENABLE                
  #define EIINT375_ENABLE                 0x00000000u
#endif

// #define EIINT376_ENABLE                 (IRQ_TABLE_START + 0x000005E0u)
#ifndef EIINT376_ENABLE                
  #define EIINT376_ENABLE                 0x00000000u
#endif

// #define EIINT377_ENABLE                 (IRQ_TABLE_START + 0x000005E4u)
#ifndef EIINT377_ENABLE                
  #define EIINT377_ENABLE                 0x00000000u
#endif

// #define EIINT378_ENABLE                 (IRQ_TABLE_START + 0x000005E8u)
#ifndef EIINT378_ENABLE                
  #define EIINT378_ENABLE                 0x00000000u
#endif

// #define EIINT379_ENABLE                 (IRQ_TABLE_START + 0x000005ECu)
#ifndef EIINT379_ENABLE                
  #define EIINT379_ENABLE                 0x00000000u
#endif

// #define EIINT380_ENABLE                 (IRQ_TABLE_START + 0x000005F0u)
#ifndef EIINT380_ENABLE                
  #define EIINT380_ENABLE                 0x00000000u
#endif

// #define EIINT381_ENABLE                 (IRQ_TABLE_START + 0x000005F4u)
#ifndef EIINT381_ENABLE                
  #define EIINT381_ENABLE                 0x00000000u
#endif

// #define EIINT382_ENABLE                 (IRQ_TABLE_START + 0x000005F8u)
#ifndef EIINT382_ENABLE                
  #define EIINT382_ENABLE                 0x00000000u
#endif

// #define EIINT383_ENABLE                 (IRQ_TABLE_START + 0x000005FCu)
#ifndef EIINT383_ENABLE                
  #define EIINT383_ENABLE                 0x00000000u
#endif

// #define EIINT384_ENABLE                 (IRQ_TABLE_START + 0x00000600u)
#ifndef EIINT384_ENABLE                
  #define EIINT384_ENABLE                 0x00000000u
#endif

// #define EIINT385_ENABLE                 (IRQ_TABLE_START + 0x00000604u)
#ifndef EIINT385_ENABLE                
  #define EIINT385_ENABLE                 0x00000000u
#endif

// #define EIINT386_ENABLE                 (IRQ_TABLE_START + 0x00000608u)
#ifndef EIINT386_ENABLE                
  #define EIINT386_ENABLE                 0x00000000u
#endif

// #define EIINT387_ENABLE                 (IRQ_TABLE_START + 0x0000060Cu)
#ifndef EIINT387_ENABLE                
  #define EIINT387_ENABLE                 0x00000000u
#endif

// #define EIINT388_ENABLE                 (IRQ_TABLE_START + 0x00000610u)
#ifndef EIINT388_ENABLE                
  #define EIINT388_ENABLE                 0x00000000u
#endif

// #define EIINT389_ENABLE                 (IRQ_TABLE_START + 0x00000614u)
#ifndef EIINT389_ENABLE                
  #define EIINT389_ENABLE                 0x00000000u
#endif

// #define EIINT390_ENABLE                 (IRQ_TABLE_START + 0x00000618u)
#ifndef EIINT390_ENABLE                
  #define EIINT390_ENABLE                 0x00000000u
#endif

// #define EIINT391_ENABLE                 (IRQ_TABLE_START + 0x0000061Cu)
#ifndef EIINT391_ENABLE                
  #define EIINT391_ENABLE                 0x00000000u
#endif

// #define EIINT392_ENABLE                 (IRQ_TABLE_START + 0x00000620u)
#ifndef EIINT392_ENABLE                
  #define EIINT392_ENABLE                 0x00000000u
#endif

// #define EIINT393_ENABLE                 (IRQ_TABLE_START + 0x00000624u)
#ifndef EIINT393_ENABLE                
  #define EIINT393_ENABLE                 0x00000000u
#endif

// #define EIINT394_ENABLE                 (IRQ_TABLE_START + 0x00000628u)
#ifndef EIINT394_ENABLE                
  #define EIINT394_ENABLE                 0x00000000u
#endif

// #define EIINT395_ENABLE                 (IRQ_TABLE_START + 0x0000062Cu)
#ifndef EIINT395_ENABLE                
  #define EIINT395_ENABLE                 0x00000000u
#endif

// #define EIINT396_ENABLE                 (IRQ_TABLE_START + 0x00000630u)
#ifndef EIINT396_ENABLE                
  #define EIINT396_ENABLE                 0x00000000u
#endif

// #define EIINT397_ENABLE                 (IRQ_TABLE_START + 0x00000634u)
#ifndef EIINT397_ENABLE                
  #define EIINT397_ENABLE                 0x00000000u
#endif

// #define EIINT398_ENABLE                 (IRQ_TABLE_START + 0x00000638u)
#ifndef EIINT398_ENABLE                
  #define EIINT398_ENABLE                 0x00000000u
#endif

// #define EIINT399_ENABLE                 (IRQ_TABLE_START + 0x0000063Cu)
#ifndef EIINT399_ENABLE                
  #define EIINT399_ENABLE                 0x00000000u
#endif

// #define EIINT400_ENABLE                 (IRQ_TABLE_START + 0x00000640u)
#ifndef EIINT400_ENABLE                
  #define EIINT400_ENABLE                 0x00000000u
#endif

// #define EIINT401_ENABLE                 (IRQ_TABLE_START + 0x00000644u)
#ifndef EIINT401_ENABLE                
  #define EIINT401_ENABLE                 0x00000000u
#endif

// #define EIINT402_ENABLE                 (IRQ_TABLE_START + 0x00000648u)
#ifndef EIINT402_ENABLE                
  #define EIINT402_ENABLE                 0x00000000u
#endif

// #define EIINT403_ENABLE                 (IRQ_TABLE_START + 0x0000064Cu)
#ifndef EIINT403_ENABLE                
  #define EIINT403_ENABLE                 0x00000000u
#endif

// #define EIINT404_ENABLE                 (IRQ_TABLE_START + 0x00000650u)
#ifndef EIINT404_ENABLE                
  #define EIINT404_ENABLE                 0x00000000u
#endif

// #define EIINT405_ENABLE                 (IRQ_TABLE_START + 0x00000654u)
#ifndef EIINT405_ENABLE                
  #define EIINT405_ENABLE                 0x00000000u
#endif

// #define EIINT406_ENABLE                 (IRQ_TABLE_START + 0x00000658u)
#ifndef EIINT406_ENABLE                
  #define EIINT406_ENABLE                 0x00000000u
#endif

// #define EIINT407_ENABLE                 (IRQ_TABLE_START + 0x0000065Cu)
#ifndef EIINT407_ENABLE                
  #define EIINT407_ENABLE                 0x00000000u
#endif

// #define EIINT408_ENABLE                 (IRQ_TABLE_START + 0x00000660u)
#ifndef EIINT408_ENABLE                
  #define EIINT408_ENABLE                 0x00000000u
#endif

// #define EIINT409_ENABLE                 (IRQ_TABLE_START + 0x00000664u)
#ifndef EIINT409_ENABLE                
  #define EIINT409_ENABLE                 0x00000000u
#endif

// #define EIINT410_ENABLE                 (IRQ_TABLE_START + 0x00000668u)
#ifndef EIINT410_ENABLE                
  #define EIINT410_ENABLE                 0x00000000u
#endif

// #define EIINT411_ENABLE                 (IRQ_TABLE_START + 0x0000066Cu)
#ifndef EIINT411_ENABLE                
  #define EIINT411_ENABLE                 0x00000000u
#endif

// #define EIINT412_ENABLE                 (IRQ_TABLE_START + 0x00000670u)
#ifndef EIINT412_ENABLE                
  #define EIINT412_ENABLE                 0x00000000u
#endif

// #define EIINT413_ENABLE                 (IRQ_TABLE_START + 0x00000674u)
#ifndef EIINT413_ENABLE                
  #define EIINT413_ENABLE                 0x00000000u
#endif

// #define EIINT414_ENABLE                 (IRQ_TABLE_START + 0x00000678u)
#ifndef EIINT414_ENABLE                
  #define EIINT414_ENABLE                 0x00000000u
#endif

// #define EIINT415_ENABLE                 (IRQ_TABLE_START + 0x0000067Cu)
#ifndef EIINT415_ENABLE                
  #define EIINT415_ENABLE                 0x00000000u
#endif

// #define EIINT416_ENABLE                 (IRQ_TABLE_START + 0x00000680u)
#ifndef EIINT416_ENABLE                
  #define EIINT416_ENABLE                 0x00000000u
#endif

// #define EIINT417_ENABLE                 (IRQ_TABLE_START + 0x00000684u)
#ifndef EIINT417_ENABLE                
  #define EIINT417_ENABLE                 0x00000000u
#endif

// #define EIINT418_ENABLE                 (IRQ_TABLE_START + 0x00000688u)
#ifndef EIINT418_ENABLE                
  #define EIINT418_ENABLE                 0x00000000u
#endif

// #define EIINT419_ENABLE                 (IRQ_TABLE_START + 0x0000068Cu)
#ifndef EIINT419_ENABLE                
  #define EIINT419_ENABLE                 0x00000000u
#endif

// #define EIINT420_ENABLE                 (IRQ_TABLE_START + 0x00000690u)
#ifndef EIINT420_ENABLE                
  #define EIINT420_ENABLE                 0x00000000u
#endif

// #define EIINT421_ENABLE                 (IRQ_TABLE_START + 0x00000694u)
#ifndef EIINT421_ENABLE                
  #define EIINT421_ENABLE                 0x00000000u
#endif

// #define EIINT422_ENABLE                 (IRQ_TABLE_START + 0x00000698u)
#ifndef EIINT422_ENABLE                
  #define EIINT422_ENABLE                 0x00000000u
#endif

// #define EIINT423_ENABLE                 (IRQ_TABLE_START + 0x0000069Cu)
#ifndef EIINT423_ENABLE                
  #define EIINT423_ENABLE                 0x00000000u
#endif

// #define EIINT424_ENABLE                 (IRQ_TABLE_START + 0x000006A0u)
#ifndef EIINT424_ENABLE                
  #define EIINT424_ENABLE                 0x00000000u
#endif

// #define EIINT425_ENABLE                 (IRQ_TABLE_START + 0x000006A4u)
#ifndef EIINT425_ENABLE                
  #define EIINT425_ENABLE                 0x00000000u
#endif

// #define EIINT426_ENABLE                 (IRQ_TABLE_START + 0x000006A8u)
#ifndef EIINT426_ENABLE                
  #define EIINT426_ENABLE                 0x00000000u
#endif

// #define EIINT427_ENABLE                 (IRQ_TABLE_START + 0x000006ACu)
#ifndef EIINT427_ENABLE                
  #define EIINT427_ENABLE                 0x00000000u
#endif

// #define EIINT428_ENABLE                 (IRQ_TABLE_START + 0x000006B0u)
#ifndef EIINT428_ENABLE                
  #define EIINT428_ENABLE                 0x00000000u
#endif

// #define EIINT429_ENABLE                 (IRQ_TABLE_START + 0x000006B4u)
#ifndef EIINT429_ENABLE                
  #define EIINT429_ENABLE                 0x00000000u
#endif

// #define EIINT430_ENABLE                 (IRQ_TABLE_START + 0x000006B8u)
#ifndef EIINT430_ENABLE                
  #define EIINT430_ENABLE                 0x00000000u
#endif

// #define EIINT431_ENABLE                 (IRQ_TABLE_START + 0x000006BCu)
#ifndef EIINT431_ENABLE                
  #define EIINT431_ENABLE                 0x00000000u
#endif

// #define EIINT432_ENABLE                 (IRQ_TABLE_START + 0x000006C0u)
#ifndef EIINT432_ENABLE                
  #define EIINT432_ENABLE                 0x00000000u
#endif

// #define EIINT433_ENABLE                 (IRQ_TABLE_START + 0x000006C4u)
#ifndef EIINT433_ENABLE                
  #define EIINT433_ENABLE                 0x00000000u
#endif

// #define EIINT434_ENABLE                 (IRQ_TABLE_START + 0x000006C8u)
#ifndef EIINT434_ENABLE                
  #define EIINT434_ENABLE                 0x00000000u
#endif

// #define EIINT435_ENABLE                 (IRQ_TABLE_START + 0x000006CCu)
#ifndef EIINT435_ENABLE                
  #define EIINT435_ENABLE                 0x00000000u
#endif

// #define EIINT436_ENABLE                 (IRQ_TABLE_START + 0x000006D0u)
#ifndef EIINT436_ENABLE                
  #define EIINT436_ENABLE                 0x00000000u
#endif

// #define EIINT437_ENABLE                 (IRQ_TABLE_START + 0x000006D4u)
#ifndef EIINT437_ENABLE                
  #define EIINT437_ENABLE                 0x00000000u
#endif

// #define EIINT438_ENABLE                 (IRQ_TABLE_START + 0x000006D8u)
#ifndef EIINT438_ENABLE                
  #define EIINT438_ENABLE                 0x00000000u
#endif

// #define EIINT439_ENABLE                 (IRQ_TABLE_START + 0x000006DCu)
#ifndef EIINT439_ENABLE                
  #define EIINT439_ENABLE                 0x00000000u
#endif

// #define EIINT440_ENABLE                 (IRQ_TABLE_START + 0x000006E0u)
#ifndef EIINT440_ENABLE                
  #define EIINT440_ENABLE                 0x00000000u
#endif

// #define EIINT441_ENABLE                 (IRQ_TABLE_START + 0x000006E4u)
#ifndef EIINT441_ENABLE                
  #define EIINT441_ENABLE                 0x00000000u
#endif

// #define EIINT442_ENABLE                 (IRQ_TABLE_START + 0x000006E8u)
#ifndef EIINT442_ENABLE                
  #define EIINT442_ENABLE                 0x00000000u
#endif

// #define EIINT443_ENABLE                 (IRQ_TABLE_START + 0x000006ECu)
#ifndef EIINT443_ENABLE                
  #define EIINT443_ENABLE                 0x00000000u
#endif

// #define EIINT444_ENABLE                 (IRQ_TABLE_START + 0x000006F0u)
#ifndef EIINT444_ENABLE                
  #define EIINT444_ENABLE                 0x00000000u
#endif

// #define EIINT445_ENABLE                 (IRQ_TABLE_START + 0x000006F4u)
#ifndef EIINT445_ENABLE                
  #define EIINT445_ENABLE                 0x00000000u
#endif

// #define EIINT446_ENABLE                 (IRQ_TABLE_START + 0x000006F8u)
#ifndef EIINT446_ENABLE                
  #define EIINT446_ENABLE                 0x00000000u
#endif

// #define EIINT447_ENABLE                 (IRQ_TABLE_START + 0x000006FCu)
#ifndef EIINT447_ENABLE                
  #define EIINT447_ENABLE                 0x00000000u
#endif

// #define EIINT448_ENABLE                 (IRQ_TABLE_START + 0x00000700u)
#ifndef EIINT448_ENABLE                
  #define EIINT448_ENABLE                 0x00000000u
#endif

// #define EIINT449_ENABLE                 (IRQ_TABLE_START + 0x00000704u)
#ifndef EIINT449_ENABLE                
  #define EIINT449_ENABLE                 0x00000000u
#endif

// #define EIINT450_ENABLE                 (IRQ_TABLE_START + 0x00000708u)
#ifndef EIINT450_ENABLE                
  #define EIINT450_ENABLE                 0x00000000u
#endif

// #define EIINT451_ENABLE                 (IRQ_TABLE_START + 0x0000070Cu)
#ifndef EIINT451_ENABLE                
  #define EIINT451_ENABLE                 0x00000000u
#endif

// #define EIINT452_ENABLE                 (IRQ_TABLE_START + 0x00000710u)
#ifndef EIINT452_ENABLE                
  #define EIINT452_ENABLE                 0x00000000u
#endif

// #define EIINT453_ENABLE                 (IRQ_TABLE_START + 0x00000714u)
#ifndef EIINT453_ENABLE                
  #define EIINT453_ENABLE                 0x00000000u
#endif

// #define EIINT454_ENABLE                 (IRQ_TABLE_START + 0x00000718u)
#ifndef EIINT454_ENABLE                
  #define EIINT454_ENABLE                 0x00000000u
#endif

// #define EIINT455_ENABLE                 (IRQ_TABLE_START + 0x0000071Cu)
#ifndef EIINT455_ENABLE                
  #define EIINT455_ENABLE                 0x00000000u
#endif

// #define EIINT456_ENABLE                 (IRQ_TABLE_START + 0x00000720u)
#ifndef EIINT456_ENABLE                
  #define EIINT456_ENABLE                 0x00000000u
#endif

// #define EIINT457_ENABLE                 (IRQ_TABLE_START + 0x00000724u)
#ifndef EIINT457_ENABLE                
  #define EIINT457_ENABLE                 0x00000000u
#endif

// #define EIINT458_ENABLE                 (IRQ_TABLE_START + 0x00000728u)
#ifndef EIINT458_ENABLE                
  #define EIINT458_ENABLE                 0x00000000u
#endif

// #define EIINT459_ENABLE                 (IRQ_TABLE_START + 0x0000072Cu)
#ifndef EIINT459_ENABLE                
  #define EIINT459_ENABLE                 0x00000000u
#endif

// #define EIINT460_ENABLE                 (IRQ_TABLE_START + 0x00000730u)
#ifndef EIINT460_ENABLE                
  #define EIINT460_ENABLE                 0x00000000u
#endif

// #define EIINT461_ENABLE                 (IRQ_TABLE_START + 0x00000734u)
#ifndef EIINT461_ENABLE                
  #define EIINT461_ENABLE                 0x00000000u
#endif

// #define EIINT462_ENABLE                 (IRQ_TABLE_START + 0x00000738u)
#ifndef EIINT462_ENABLE                
  #define EIINT462_ENABLE                 0x00000000u
#endif

// #define EIINT463_ENABLE                 (IRQ_TABLE_START + 0x0000073Cu)
#ifndef EIINT463_ENABLE                
  #define EIINT463_ENABLE                 0x00000000u
#endif

// #define EIINT464_ENABLE                 (IRQ_TABLE_START + 0x00000740u)
#ifndef EIINT464_ENABLE                
  #define EIINT464_ENABLE                 0x00000000u
#endif

// #define EIINT465_ENABLE                 (IRQ_TABLE_START + 0x00000744u)
#ifndef EIINT465_ENABLE                
  #define EIINT465_ENABLE                 0x00000000u
#endif

// #define EIINT466_ENABLE                 (IRQ_TABLE_START + 0x00000748u)
#ifndef EIINT466_ENABLE                
  #define EIINT466_ENABLE                 0x00000000u
#endif

// #define EIINT467_ENABLE                 (IRQ_TABLE_START + 0x0000074Cu)
#ifndef EIINT467_ENABLE                
  #define EIINT467_ENABLE                 0x00000000u
#endif

// #define EIINT468_ENABLE                 (IRQ_TABLE_START + 0x00000750u)
#ifndef EIINT468_ENABLE                
  #define EIINT468_ENABLE                 0x00000000u
#endif

// #define EIINT469_ENABLE                 (IRQ_TABLE_START + 0x00000754u)
#ifndef EIINT469_ENABLE                
  #define EIINT469_ENABLE                 0x00000000u
#endif

// #define EIINT470_ENABLE                 (IRQ_TABLE_START + 0x00000758u)
#ifndef EIINT470_ENABLE                
  #define EIINT470_ENABLE                 0x00000000u
#endif

// #define EIINT471_ENABLE                 (IRQ_TABLE_START + 0x0000075Cu)
#ifndef EIINT471_ENABLE                
  #define EIINT471_ENABLE                 0x00000000u
#endif

// #define EIINT472_ENABLE                 (IRQ_TABLE_START + 0x00000760u)
#ifndef EIINT472_ENABLE                
  #define EIINT472_ENABLE                 0x00000000u
#endif

// #define EIINT473_ENABLE                 (IRQ_TABLE_START + 0x00000764u)
#ifndef EIINT473_ENABLE                
  #define EIINT473_ENABLE                 0x00000000u
#endif

// #define EIINT474_ENABLE                 (IRQ_TABLE_START + 0x00000768u)
#ifndef EIINT474_ENABLE                
  #define EIINT474_ENABLE                 0x00000000u
#endif

// #define EIINT475_ENABLE                 (IRQ_TABLE_START + 0x0000076Cu)
#ifndef EIINT475_ENABLE                
  #define EIINT475_ENABLE                 0x00000000u
#endif

// #define EIINT476_ENABLE                 (IRQ_TABLE_START + 0x00000770u)
#ifndef EIINT476_ENABLE                
  #define EIINT476_ENABLE                 0x00000000u
#endif

// #define EIINT477_ENABLE                 (IRQ_TABLE_START + 0x00000774u)
#ifndef EIINT477_ENABLE                
  #define EIINT477_ENABLE                 0x00000000u
#endif

// #define EIINT478_ENABLE                 (IRQ_TABLE_START + 0x00000778u)
#ifndef EIINT478_ENABLE                
  #define EIINT478_ENABLE                 0x00000000u
#endif

// #define EIINT479_ENABLE                 (IRQ_TABLE_START + 0x0000077Cu)
#ifndef EIINT479_ENABLE                
  #define EIINT479_ENABLE                 0x00000000u
#endif

// #define EIINT480_ENABLE                 (IRQ_TABLE_START + 0x00000780u)
#ifndef EIINT480_ENABLE                
  #define EIINT480_ENABLE                 0x00000000u
#endif

// #define EIINT481_ENABLE                 (IRQ_TABLE_START + 0x00000784u)
#ifndef EIINT481_ENABLE                
  #define EIINT481_ENABLE                 0x00000000u
#endif

// #define EIINT482_ENABLE                 (IRQ_TABLE_START + 0x00000788u)
#ifndef EIINT482_ENABLE                
  #define EIINT482_ENABLE                 0x00000000u
#endif

// #define EIINT483_ENABLE                 (IRQ_TABLE_START + 0x0000078Cu)
#ifndef EIINT483_ENABLE                
  #define EIINT483_ENABLE                 0x00000000u
#endif

// #define EIINT484_ENABLE                 (IRQ_TABLE_START + 0x00000790u)
#ifndef EIINT484_ENABLE                
  #define EIINT484_ENABLE                 0x00000000u
#endif

// #define EIINT485_ENABLE                 (IRQ_TABLE_START + 0x00000794u)
#ifndef EIINT485_ENABLE                
  #define EIINT485_ENABLE                 0x00000000u
#endif

// #define EIINT486_ENABLE                 (IRQ_TABLE_START + 0x00000798u)
#ifndef EIINT486_ENABLE                
  #define EIINT486_ENABLE                 0x00000000u
#endif

// #define EIINT487_ENABLE                 (IRQ_TABLE_START + 0x0000079Cu)
#ifndef EIINT487_ENABLE                
  #define EIINT487_ENABLE                 0x00000000u
#endif

// #define EIINT488_ENABLE                 (IRQ_TABLE_START + 0x000007A0u)
#ifndef EIINT488_ENABLE                
  #define EIINT488_ENABLE                 0x00000000u
#endif

// #define EIINT489_ENABLE                 (IRQ_TABLE_START + 0x000007A4u)
#ifndef EIINT489_ENABLE                
  #define EIINT489_ENABLE                 0x00000000u
#endif

// #define EIINT490_ENABLE                 (IRQ_TABLE_START + 0x000007A8u)
#ifndef EIINT490_ENABLE                
  #define EIINT490_ENABLE                 0x00000000u
#endif

// #define EIINT491_ENABLE                 (IRQ_TABLE_START + 0x000007ACu)
#ifndef EIINT491_ENABLE                
  #define EIINT491_ENABLE                 0x00000000u
#endif

// #define EIINT492_ENABLE                 (IRQ_TABLE_START + 0x000007B0u)
#ifndef EIINT492_ENABLE                
  #define EIINT492_ENABLE                 0x00000000u
#endif

// #define EIINT493_ENABLE                 (IRQ_TABLE_START + 0x000007B4u)
#ifndef EIINT493_ENABLE                
  #define EIINT493_ENABLE                 0x00000000u
#endif

// #define EIINT494_ENABLE                 (IRQ_TABLE_START + 0x000007B8u)
#ifndef EIINT494_ENABLE                
  #define EIINT494_ENABLE                 0x00000000u
#endif

// #define EIINT495_ENABLE                 (IRQ_TABLE_START + 0x000007BCu)
#ifndef EIINT495_ENABLE                
  #define EIINT495_ENABLE                 0x00000000u
#endif

// #define EIINT496_ENABLE                 (IRQ_TABLE_START + 0x000007C0u)
#ifndef EIINT496_ENABLE                
  #define EIINT496_ENABLE                 0x00000000u
#endif



#endif /* __R7F702Z19_IRQ_H */
